import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,'Content-Type':'application/json'}});
const APIFY='https://api.apify.com/v2/acts';

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});
 const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,db=createClient(url,key);
 try{
  const auth=req.headers.get('authorization')||'';if(auth.replace(/^Bearer\s+/i,'')!==key)return json({error:'Internal only'},403);
  const {propertyId,country='GE',maxSources=8,postsPerSource=5}=await req.json();const token=Deno.env.get('APIFY_API_TOKEN')!;if(!token)return json({error:'APIFY token missing'},500);
  const {data:sources}=await db.from('source_registry').select('id,platform,url,name,last_collected_at,priority').eq('active',true).eq('country_code',String(country).toUpperCase()).in('platform',['FACEBOOK','VK']).order('last_collected_at',{ascending:true,nullsFirst:true}).order('priority',{ascending:false}).limit(Math.min(100,Math.max(1,Number(maxSources)||8)));
  const fb=(sources||[]).filter((s:any)=>s.platform==='FACEBOOK'),vk=(sources||[]).filter((s:any)=>s.platform==='VK');let inserted=0,skipped=0;const errors:any[]=[];
  for(let i=0;i<fb.length;i+=25){const batch=fb.slice(i,i+25);try{const items=await runActor(token,'apify~facebook-groups-scraper',{startUrls:batch.map((s:any)=>({url:s.url})),resultsLimit:Math.max(1,Math.min(20,Number(postsPerSource)||5)),viewOption:'CHRONOLOGICAL',onlyPostsNewerThan:'30 days'},150000);for(const x of items){const src=batch.find((s:any)=>sameGroup(s.url,x.inputUrl||x.facebookUrl||''));const text=String(x.text||'').trim();if(text.length<20){skipped++;continue}const ok=await saveSignal(db,src?.id||null,'FACEBOOK',x.id||x.legacyId||x.url,x.url||null,text,x.user?.name||null,x.user?.profileUrl||null,x.time||null);ok?inserted++:skipped++;}for(const s of batch)await db.from('source_registry').update({last_collected_at:new Date().toISOString(),last_successful_at:new Date().toISOString()}).eq('id',s.id)}catch(e){errors.push({platform:'FACEBOOK',error:e instanceof Error?e.message:String(e)});}}
  for(let i=0;i<vk.length;i+=50){const batch=vk.slice(i,i+50);try{const items=await runActor(token,'automation-lab~vk-posts-scraper',{startUrls:batch.map((s:any)=>({url:s.url})),maxPostsPerUrl:Math.max(1,Math.min(20,Number(postsPerSource)||5)),includeAttachments:false},120000);for(const x of items){const text=String(x.text||x.postText||'').trim();if(text.length<20){skipped++;continue}const sourceUrl=x.sourceUrl||x.ownerUrl||x.profileUrl||null;const src=batch.find((s:any)=>sourceUrl&&sourceUrl.includes(new URL(s.url).pathname.replace('/','')));const ok=await saveSignal(db,src?.id||null,'VK',x.postId||x.id||x.postUrl,x.postUrl||x.url||null,text,x.ownerName||x.author||null,x.ownerUrl||null,x.date||x.publishedAt||null);ok?inserted++:skipped++;}for(const s of batch)await db.from('source_registry').update({last_collected_at:new Date().toISOString(),last_successful_at:new Date().toISOString()}).eq('id',s.id)}catch(e){errors.push({platform:'VK',error:e instanceof Error?e.message:String(e)});}}
  await db.from('cost_events').insert({provider:'APIFY',operation_type:'SOURCE_MONITOR_PUBLIC',source:'registry-rotating',market:String(country).toUpperCase(),units:(fb.length+vk.length),cost_usd:0,success:errors.length===0,cache_hit:false,property_id:propertyId||null});
  return json({success:true,sourcesRead:fb.length+vk.length,facebookSources:fb.length,vkSources:vk.length,signalsInserted:inserted,signalsSkipped:skipped,errors});
 }catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}
});
async function runActor(token:string,actor:string,input:any,timeout:number){const r=await fetch(`${APIFY}/${actor}/run-sync-get-dataset-items?timeout=${Math.floor(timeout/1000)-5}&memory=1024`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(input),signal:AbortSignal.timeout(timeout)});if(!r.ok)throw new Error(`${actor} ${r.status}: ${(await r.text()).slice(0,350)}`);const d=await r.json();return Array.isArray(d)?d:[]}
function sameGroup(a:string,b:string){try{return new URL(a).pathname.split('/').filter(Boolean).slice(0,2).join('/')===new URL(b).pathname.split('/').filter(Boolean).slice(0,2).join('/')}catch{return false}}
async function saveSignal(db:any,sourceId:string|null,platform:string,externalId:any,url:string|null,text:string,author:string|null,profile:string|null,date:any){const fp=await fingerprint(text);const {error}=await db.from('raw_signals').insert({source_id:sourceId,platform,external_id:String(externalId||url||fp),source_url:url,author_public_name:author,author_public_url:profile,original_text:text,published_at:date||null,content_fingerprint:fp,provider:'APIFY',classification_status:'PENDING',mock_mode:false});return !error}
async function fingerprint(t:string){const b=new TextEncoder().encode(t.toLowerCase().replace(/\s+/g,' ').trim().slice(0,500));const h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).slice(0,16).map(x=>x.toString(16).padStart(2,'0')).join('')}
