// THE PUBLIC SHARE VIEWER'S WORDS, IN ALL SIX LANGUAGES.
//
// The viewer is its own small bundle (share.html), so it does not load the
// app's full translation file. Room and walkthrough words MIRROR
// src/i18n/translations.ts; src/share/__tests__/strings.test.mjs keeps them
// identical and every locale complete.

export const SHARE_LANGS = ['en', 'ka', 'ru', 'tr', 'ar', 'he'] as const;
export type ShareLang = typeof SHARE_LANGS[number];

export const SHARE_STRINGS: Record<ShareLang, Record<string, string>> = {
  en: {
    ds_room_living: "Living room",
    ds_room_bedroom: "Bedroom",
    ds_room_kitchen: "Kitchen",
    ds_room_bathroom: "Bathroom",
    ds_room_wc: "WC",
    ds_room_hall: "Hall",
    ds_room_corridor: "Corridor",
    ds_room_storage: "Storage",
    ds_room_balcony: "Balcony",
    ds_room_terrace: "Terrace",
    ds_room_unknown: "Room",
    ds_walk_title: "Walkthrough",
    ds_walk_reset: "Back to the entrance",
    ds_walk_rooms: "Go to a room",
    ds_walk_joystick: "Walk: drag to move",
    share_loading: "Preparing the walkthrough…",
    share_brand_line: "Designed in HOMATCH Design Studio",
    share_enter: "Enter walkthrough",
    share_estimated: "Sizes are approximate: this space was drawn from a floor plan.",
    share_preview_note: "A design preview. Colours, materials and light can look different in reality.",
    share_overview: "Overview",
    share_help_keys: "W A S D or arrows to walk · drag to look",
    share_tour_play: "Guided tour",
    share_tour_pause: "Pause tour",
    share_fullscreen: "Full screen",
    share_language: "Language",
    share_revoked_title: "This link is no longer shared",
    share_revoked_body: "The owner has stopped sharing this design. Ask them for a new link.",
    share_expired_title: "This link has expired",
    share_expired_body: "Links can be shared for a limited time. Ask the owner for a new one.",
    share_not_found_title: "This link does not open anything",
    share_not_found_body: "Check that the whole link was copied.",
    share_unavailable_title: "This design cannot be shown",
    share_unavailable_body: "The space it was made in is no longer available.",
    share_error_title: "The walkthrough could not load",
    share_error_body: "Check your connection and try again.",
    share_retry: "Try again",
    share_webgl: "This device cannot show 3D."
  },
  ka: {
    ds_room_living: "მისაღები",
    ds_room_bedroom: "საძინებელი",
    ds_room_kitchen: "სამზარეულო",
    ds_room_bathroom: "სააბაზანო",
    ds_room_wc: "საპირფარეშო",
    ds_room_hall: "ჰოლი",
    ds_room_corridor: "დერეფანი",
    ds_room_storage: "სათავსო",
    ds_room_balcony: "აივანი",
    ds_room_terrace: "ტერასა",
    ds_room_unknown: "ოთახი",
    ds_walk_title: "გავლა",
    ds_walk_reset: "შესასვლელთან დაბრუნება",
    ds_walk_rooms: "ოთახში გადასვლა",
    ds_walk_joystick: "გავლა: გადაათრიეთ სამოძრაოდ",
    share_loading: "გავლა მზადდება…",
    share_brand_line: "შექმნილია HOMATCH Design Studio-ში",
    share_enter: "შიგნით შესვლა",
    share_estimated: "ზომები მიახლოებითია: სივრცე გეგმიდანაა აგებული.",
    share_preview_note: "დიზაინის წინასწარი ხედი. ფერები, მასალები და განათება რეალობაში შეიძლება განსხვავდებოდეს.",
    share_overview: "მიმოხილვა",
    share_help_keys: "W A S D ან ისრები სავალად · გადაათრიეთ სახედად",
    share_tour_play: "გიდიანი ტური",
    share_tour_pause: "ტურის შეჩერება",
    share_fullscreen: "სრული ეკრანი",
    share_language: "ენა",
    share_revoked_title: "ეს ბმული აღარ არის გაზიარებული",
    share_revoked_body: "მფლობელმა ამ დიზაინის გაზიარება შეწყვიტა. სთხოვეთ ახალი ბმული.",
    share_expired_title: "ამ ბმულს ვადა გაუვიდა",
    share_expired_body: "ბმულები შეიძლება დროებით ზიარდებოდეს. სთხოვეთ მფლობელს ახალი.",
    share_not_found_title: "ეს ბმული არაფერს ხსნის",
    share_not_found_body: "შეამოწმეთ, რომ მთელი ბმული დაკოპირდა.",
    share_unavailable_title: "ამ დიზაინის ჩვენება შეუძლებელია",
    share_unavailable_body: "სივრცე, რომელშიც ის შეიქმნა, აღარ არის ხელმისაწვდომი.",
    share_error_title: "გავლა ვერ ჩაიტვირთა",
    share_error_body: "შეამოწმეთ კავშირი და სცადეთ ხელახლა.",
    share_retry: "ხელახლა ცდა",
    share_webgl: "ამ მოწყობილობას 3D-ის ჩვენება არ შეუძლია."
  },
  ru: {
    ds_room_living: "Гостиная",
    ds_room_bedroom: "Спальня",
    ds_room_kitchen: "Кухня",
    ds_room_bathroom: "Ванная",
    ds_room_wc: "Туалет",
    ds_room_hall: "Прихожая",
    ds_room_corridor: "Коридор",
    ds_room_storage: "Кладовая",
    ds_room_balcony: "Балкон",
    ds_room_terrace: "Терраса",
    ds_room_unknown: "Комната",
    ds_walk_title: "Прогулка",
    ds_walk_reset: "К входу",
    ds_walk_rooms: "Перейти в комнату",
    ds_walk_joystick: "Ходьба: потяните, чтобы двигаться",
    share_loading: "Готовим прогулку…",
    share_brand_line: "Создано в HOMATCH Design Studio",
    share_enter: "Начать прогулку",
    share_estimated: "Размеры приблизительные: пространство построено по планировке.",
    share_preview_note: "Предварительный вид дизайна. В реальности цвета, материалы и свет могут выглядеть иначе.",
    share_overview: "Общий вид",
    share_help_keys: "W A S D или стрелки — идти · перетаскивание — смотреть",
    share_tour_play: "Экскурсия",
    share_tour_pause: "Пауза",
    share_fullscreen: "Во весь экран",
    share_language: "Язык",
    share_revoked_title: "Эта ссылка больше не действует",
    share_revoked_body: "Владелец больше не делится этим дизайном. Попросите у него новую ссылку.",
    share_expired_title: "Срок действия ссылки истёк",
    share_expired_body: "Ссылки могут действовать ограниченное время. Попросите у владельца новую.",
    share_not_found_title: "Эта ссылка ничего не открывает",
    share_not_found_body: "Проверьте, что ссылка скопирована полностью.",
    share_unavailable_title: "Этот дизайн нельзя показать",
    share_unavailable_body: "Пространство, в котором он создан, больше недоступно.",
    share_error_title: "Не удалось загрузить прогулку",
    share_error_body: "Проверьте соединение и попробуйте снова.",
    share_retry: "Попробовать снова",
    share_webgl: "Это устройство не может показать 3D."
  },
  tr: {
    ds_room_living: "Oturma odası",
    ds_room_bedroom: "Yatak odası",
    ds_room_kitchen: "Mutfak",
    ds_room_bathroom: "Banyo",
    ds_room_wc: "Tuvalet",
    ds_room_hall: "Hol",
    ds_room_corridor: "Koridor",
    ds_room_storage: "Depo",
    ds_room_balcony: "Balkon",
    ds_room_terrace: "Teras",
    ds_room_unknown: "Oda",
    ds_walk_title: "İç gezinti",
    ds_walk_reset: "Girişe dön",
    ds_walk_rooms: "Bir odaya git",
    ds_walk_joystick: "Yürü: hareket etmek için sürükleyin",
    share_loading: "İç gezinti hazırlanıyor…",
    share_brand_line: "HOMATCH Design Studio'da tasarlandı",
    share_enter: "İç gezintiye başla",
    share_estimated: "Ölçüler yaklaşıktır: bu alan bir kat planından oluşturuldu.",
    share_preview_note: "Bir tasarım önizlemesi. Renkler, malzemeler ve ışık gerçekte farklı görünebilir.",
    share_overview: "Genel görünüm",
    share_help_keys: "Yürümek için W A S D veya oklar · bakmak için sürükleyin",
    share_tour_play: "Rehberli tur",
    share_tour_pause: "Turu duraklat",
    share_fullscreen: "Tam ekran",
    share_language: "Dil",
    share_revoked_title: "Bu bağlantı artık paylaşılmıyor",
    share_revoked_body: "Sahibi bu tasarımı paylaşmayı bıraktı. Yeni bir bağlantı isteyin.",
    share_expired_title: "Bu bağlantının süresi doldu",
    share_expired_body: "Bağlantılar sınırlı bir süre paylaşılabilir. Sahibinden yenisini isteyin.",
    share_not_found_title: "Bu bağlantı hiçbir şey açmıyor",
    share_not_found_body: "Bağlantının tamamının kopyalandığını kontrol edin.",
    share_unavailable_title: "Bu tasarım gösterilemiyor",
    share_unavailable_body: "Tasarımın yapıldığı alan artık mevcut değil.",
    share_error_title: "İç gezinti yüklenemedi",
    share_error_body: "Bağlantınızı kontrol edip tekrar deneyin.",
    share_retry: "Tekrar dene",
    share_webgl: "Bu cihaz 3B gösteremiyor."
  },
  ar: {
    ds_room_living: "غرفة المعيشة",
    ds_room_bedroom: "غرفة النوم",
    ds_room_kitchen: "المطبخ",
    ds_room_bathroom: "الحمّام",
    ds_room_wc: "دورة المياه",
    ds_room_hall: "الردهة",
    ds_room_corridor: "الممر",
    ds_room_storage: "المخزن",
    ds_room_balcony: "الشرفة",
    ds_room_terrace: "التراس",
    ds_room_unknown: "غرفة",
    ds_walk_title: "جولة داخلية",
    ds_walk_reset: "العودة إلى المدخل",
    ds_walk_rooms: "الانتقال إلى غرفة",
    ds_walk_joystick: "المشي: اسحب للتحرك",
    share_loading: "جارٍ تجهيز الجولة…",
    share_brand_line: "صُمّم في HOMATCH Design Studio",
    share_enter: "ابدأ الجولة",
    share_estimated: "الأحجام تقريبية: بُنيت هذه المساحة من مخطط.",
    share_preview_note: "معاينة للتصميم. قد تبدو الألوان والمواد والإضاءة مختلفة في الواقع.",
    share_overview: "نظرة عامة",
    share_help_keys: "W A S D أو الأسهم للمشي · اسحب للنظر",
    share_tour_play: "جولة موجّهة",
    share_tour_pause: "إيقاف الجولة مؤقتًا",
    share_fullscreen: "ملء الشاشة",
    share_language: "اللغة",
    share_revoked_title: "لم يعد هذا الرابط متاحًا",
    share_revoked_body: "توقف المالك عن مشاركة هذا التصميم. اطلب منه رابطًا جديدًا.",
    share_expired_title: "انتهت صلاحية هذا الرابط",
    share_expired_body: "قد تُشارَك الروابط لفترة محدودة. اطلب من المالك رابطًا جديدًا.",
    share_not_found_title: "هذا الرابط لا يفتح شيئًا",
    share_not_found_body: "تأكد من نسخ الرابط كاملًا.",
    share_unavailable_title: "لا يمكن عرض هذا التصميم",
    share_unavailable_body: "لم تعد المساحة التي صُمّم فيها متاحة.",
    share_error_title: "تعذّر تحميل الجولة",
    share_error_body: "تحقّق من اتصالك وحاول مجددًا.",
    share_retry: "أعد المحاولة",
    share_webgl: "لا يستطيع هذا الجهاز عرض المحتوى ثلاثي الأبعاد."
  },
  he: {
    ds_room_living: "סלון",
    ds_room_bedroom: "חדר שינה",
    ds_room_kitchen: "מטבח",
    ds_room_bathroom: "חדר רחצה",
    ds_room_wc: "שירותים",
    ds_room_hall: "מבואה",
    ds_room_corridor: "מסדרון",
    ds_room_storage: "מחסן",
    ds_room_balcony: "מרפסת",
    ds_room_terrace: "מרפסת גג",
    ds_room_unknown: "חדר",
    ds_walk_title: "סיור",
    ds_walk_reset: "חזרה לכניסה",
    ds_walk_rooms: "מעבר לחדר",
    ds_walk_joystick: "הליכה: גררו כדי לזוז",
    share_loading: "מכינים את הסיור…",
    share_brand_line: "עוצב ב־HOMATCH Design Studio",
    share_enter: "כניסה לסיור",
    share_estimated: "המידות משוערות: המרחב נבנה מתוכנית קומה.",
    share_preview_note: "תצוגה מקדימה של עיצוב. צבעים, חומרים ותאורה עשויים להיראות אחרת במציאות.",
    share_overview: "מבט כללי",
    share_help_keys: "W A S D או חיצים להליכה · גררו כדי להסתכל",
    share_tour_play: "סיור מודרך",
    share_tour_pause: "השהיית הסיור",
    share_fullscreen: "מסך מלא",
    share_language: "שפה",
    share_revoked_title: "הקישור הזה כבר לא משותף",
    share_revoked_body: "הבעלים הפסיקו לשתף את העיצוב הזה. בקשו מהם קישור חדש.",
    share_expired_title: "תוקף הקישור פג",
    share_expired_body: "אפשר לשתף קישורים לזמן מוגבל. בקשו מהבעלים קישור חדש.",
    share_not_found_title: "הקישור הזה לא פותח דבר",
    share_not_found_body: "בדקו שכל הקישור הועתק.",
    share_unavailable_title: "אי אפשר להציג את העיצוב הזה",
    share_unavailable_body: "המרחב שבו הוא נוצר כבר אינו זמין.",
    share_error_title: "לא ניתן היה לטעון את הסיור",
    share_error_body: "בדקו את החיבור ונסו שוב.",
    share_retry: "נסו שוב",
    share_webgl: "המכשיר הזה לא יכול להציג תלת־ממד."
  }
};
