// THE PUBLIC SHARE VIEWER'S WORDS, IN ALL SIX LANGUAGES.
//
// The viewer is its own small bundle (share.html), so it does not load the
// app's full translation file. Room and walkthrough words MIRROR
// src/i18n/translations.ts; src/share/__tests__/strings.test.mjs keeps them
// identical and every locale complete.

export const SHARE_LANGS = ['en', 'ka', 'ru', 'tr', 'ar', 'he'] as const;
export type ShareLang = typeof SHARE_LANGS[number];

export const SHARE_STRINGS: Record<ShareLang, Record<string, string>> = {
  en: {
    ds_room_living: "Living room",
    ds_room_bedroom: "Bedroom",
    ds_room_kitchen: "Kitchen",
    ds_room_bathroom: "Bathroom",
    ds_room_wc: "WC",
    ds_room_hall: "Hall",
    ds_room_corridor: "Corridor",
    ds_room_storage: "Storage",
    ds_room_balcony: "Balcony",
    ds_room_terrace: "Terrace",
    ds_room_unknown: "Room",
    ds_walk_enter: "Walk through",
    ds_walk_exit: "Exit walkthrough",
    ds_walk_title: "Walkthrough",
    ds_walk_reset: "Back to the entrance",
    ds_walk_rooms: "Go to a room",
    ds_walk_joystick: "Walk: drag to move",
    ds_walk_help_keys: "W A S D or arrows to walk · drag to look · tap or E to open · Esc to leave",
    ds_walk_unavailable: "The walkthrough could not find a place to stand in this space.",
    ds_walk_needs_rooms: "Walking through needs room outlines, which this space does not have.",
    ds_walk_open: "Open",
    ds_walk_close: "Close",
    ds_ix_door: "Door",
    ds_ix_window: "Window",
    ds_ix_wardrobe: "Wardrobe",
    ds_ix_cabinet: "Cabinet",
    ds_ix_drawer: "Drawer",
    ds_ix_appliance: "Refrigerator",
    ds_walk_photo: "Photo",
    "ds_act_OPEN": "Open",
    "ds_act_CLOSE": "Close",
    "ds_act_TURN_ON": "Turn on",
    "ds_act_TURN_OFF": "Turn off",
    "ds_act_SIT": "Sit",
    "ds_act_LIE_DOWN": "Lie down",
    "ds_act_STAND_UP": "Stand up",
    "ds_act_MAKE_BED": "Make the bed",
    "ds_act_MESS_BED": "Mess up the bed",
    "ds_act_FLUSH": "Flush",
    "ds_act_WASH_HANDS": "Wash hands",
    "ds_act_MAKE_COFFEE": "Make coffee",
    "ds_act_DRINK": "Drink",
    "ds_act_COOK": "Cook",
    "ds_act_SERVE": "Serve",
    "ds_act_RECLINE": "Recline",
    "ds_act_SIT_UP": "Sit up",
    "ds_act_RUN_BATH": "Run a bath",
    "ds_act_DRAIN": "Drain",
    "ds_act_RAISE": "Raise",
    "ds_act_LOWER": "Lower",
    "ds_act_START": "Start",
    ds_ix_balcony_door: "Balcony door",
    ds_ix_freezer: "Freezer",
    ds_ix_oven: "Oven",
    ds_ix_dishwasher: "Dishwasher",
    ds_ix_stove: "Hob",
    ds_ix_faucet: "Tap",
    ds_ix_shower: "Shower",
    ds_ix_toilet: "Toilet",
    ds_ix_bath: "Bath",
    ds_ix_bed: "Bed",
    ds_ix_seat: "Seat",
    ds_ix_tv: "TV",
    ds_ix_light: "Light",
    ds_ix_lamp: "Lamp",
    ds_ix_curtain: "Curtains",
    ds_ix_blind: "Blind",
    ds_ix_coffee: "Coffee machine",
    ds_ix_recliner: "Recliner",
    ds_ix_mirror: "Mirror light",
    ds_env_title: "Time of day",
    "ds_env_DAY": "Day",
    "ds_env_SUNSET": "Sunset",
    "ds_env_EVENING": "Evening",
    "ds_env_NIGHT": "Night",
    ds_ctrl_title: "How to move",
    ds_ctrl_move: "Move",
    ds_ctrl_look: "Look around",
    ds_ctrl_mouse: "Mouse",
    ds_ctrl_click: "Click",
    ds_ctrl_interact: "Use what you point at",
    ds_ctrl_faster: "Walk faster",
    ds_ctrl_menu: "Menu · release the mouse",
    ds_ctrl_drag_part: "Drag a door or drawer to open it by hand",
    ds_ctrl_left_thumb: "Left thumb",
    ds_ctrl_right_thumb: "Right thumb",
    ds_ctrl_tap: "Tap an object",
    ds_ctrl_got_it: "Got it",
    ds_ctrl_dont_show: "Don’t show again",
    ds_ctrl_help: "Controls",
    ds_ctrl_click_to_look: "Click to look around with the mouse",
    ds_menu_title: "Paused",
    ds_menu_resume: "Resume",
    ds_menu_settings: "Settings",
    ds_set_title: "Walkthrough settings",
    ds_set_look: "Look sensitivity",
    ds_set_speed: "Walking pace",
    ds_set_invert: "Invert vertical look",
    ds_set_invert_x: "Invert horizontal look",
    ds_set_reduced: "Reduce motion",
    ds_set_done: "Done",
    ds_walk_seated: "Sitting",
    ds_walk_lying: "Lying down",
    ds_live_title: "Live here",
    ds_live_intro: "Small moments in this home, made from what is actually in it.",
    ds_live_coffee: "Make a coffee",
    ds_live_balcony: "Relax on the balcony",
    ds_live_tv: "Watch TV",
    ds_live_kitchen: "Explore the kitchen",
    ds_live_evening: "Evening at home",
    ds_live_dinner: "Cook dinner",
    ds_live_rest: "Rest in the bedroom",
    ds_live_step: "Step {{n}} of {{total}}",
    ds_live_walking: "Walking there…",
    ds_live_stop: "Stop",
    ds_live_finished: "Enjoy the home.",
    ds_live_none: "Nothing in this home supports these moments yet.",
    ds_live_blocked: "That spot cannot be reached from here.",
    ds_ix_washer: "Washing machine",
    ds_walk_tour_play: "Guided tour",
    ds_walk_tour_pause: "Pause tour",
    ds_walk_fullscreen: "Full screen",
    share_details: "Design details",
    share_whole_home: "Whole home",
    share_palette: "Palette",
    share_walls: "Walls",
    share_floor: "Floor",
    share_furniture: "Furniture",
    share_unchanged: "As built",
    share_no_furniture: "No furniture placed",
    share_walk_room: "Walk through this room",
    share_design_hint: "Drag to turn the home, pinch or scroll to zoom.",
    share_loading: "Preparing the walkthrough…",
    share_brand_line: "Designed in HOMATCH Design Studio",
    share_enter: "Enter walkthrough",
    share_estimated: "Sizes are approximate: this space was drawn from a floor plan.",
    share_estimated_pictures: "Sizes are approximate: this space was rebuilt from pictures.",
    share_preview_note: "A design preview. Colours, materials and light can look different in reality.",
    share_overview: "Overview",
    share_language: "Language",
    share_revoked_title: "This link is no longer shared",
    share_revoked_body: "The owner has stopped sharing this design. Ask them for a new link.",
    share_expired_title: "This link has expired",
    share_expired_body: "Links can be shared for a limited time. Ask the owner for a new one.",
    share_not_found_title: "This link does not open anything",
    share_not_found_body: "Check that the whole link was copied.",
    share_unavailable_title: "This design cannot be shown",
    share_unavailable_body: "The space it was made in is no longer available.",
    share_error_title: "The walkthrough could not load",
    share_error_body: "Check your connection and try again.",
    share_retry: "Try again",
    share_webgl: "This device cannot show 3D."
  },
  ka: {
    ds_room_living: "მისაღები",
    ds_room_bedroom: "საძინებელი",
    ds_room_kitchen: "სამზარეულო",
    ds_room_bathroom: "სააბაზანო",
    ds_room_wc: "საპირფარეშო",
    ds_room_hall: "ჰოლი",
    ds_room_corridor: "დერეფანი",
    ds_room_storage: "სათავსო",
    ds_room_balcony: "აივანი",
    ds_room_terrace: "ტერასა",
    ds_room_unknown: "ოთახი",
    ds_walk_enter: "შიგნით გავლა",
    ds_walk_exit: "გასვლა",
    ds_walk_title: "გავლა",
    ds_walk_reset: "შესასვლელთან დაბრუნება",
    ds_walk_rooms: "ოთახში გადასვლა",
    ds_walk_joystick: "გავლა: გადაათრიეთ სამოძრაოდ",
    ds_walk_help_keys: "W A S D ან ისრები სავალად · გადაათრიეთ სახედად · შეეხეთ ან E გასახსნელად · Esc გასასვლელად",
    ds_walk_unavailable: "გავლისთვის ამ სივრცეში დასადგომი ადგილი ვერ მოიძებნა.",
    ds_walk_needs_rooms: "შიგნით გავლას ოთახების კონტურები სჭირდება, რაც ამ სივრცეს არ აქვს.",
    ds_walk_open: "გახსნა",
    ds_walk_close: "დახურვა",
    ds_ix_door: "კარი",
    ds_ix_window: "ფანჯარა",
    ds_ix_wardrobe: "კარადა",
    ds_ix_cabinet: "კარადის კარი",
    ds_ix_drawer: "უჯრა",
    ds_ix_appliance: "მაცივარი",
    ds_walk_photo: "ფოტო",
    "ds_act_OPEN": "გახსნა",
    "ds_act_CLOSE": "დახურვა",
    "ds_act_TURN_ON": "ჩართვა",
    "ds_act_TURN_OFF": "გამორთვა",
    "ds_act_SIT": "დაჯდომა",
    "ds_act_LIE_DOWN": "წამოწოლა",
    "ds_act_STAND_UP": "ადგომა",
    "ds_act_MAKE_BED": "საწოლის გასწორება",
    "ds_act_MESS_BED": "საწოლის არევა",
    "ds_act_FLUSH": "ჩარეცხვა",
    "ds_act_WASH_HANDS": "ხელების დაბანა",
    "ds_act_MAKE_COFFEE": "ყავის მომზადება",
    "ds_act_DRINK": "დალევა",
    "ds_act_COOK": "მომზადება",
    "ds_act_SERVE": "გაშლა თეფშზე",
    "ds_act_RECLINE": "გადაწოლა",
    "ds_act_SIT_UP": "წამოჯდომა",
    "ds_act_RUN_BATH": "აბაზანის ავსება",
    "ds_act_DRAIN": "დაცლა",
    "ds_act_RAISE": "აწევა",
    "ds_act_LOWER": "ჩამოშვება",
    "ds_act_START": "დაწყება",
    ds_ix_balcony_door: "აივნის კარი",
    ds_ix_freezer: "საყინულე",
    ds_ix_oven: "ღუმელი",
    ds_ix_dishwasher: "ჭურჭლის სარეცხი",
    ds_ix_stove: "ქურა",
    ds_ix_faucet: "ონკანი",
    ds_ix_shower: "შხაპი",
    ds_ix_toilet: "უნიტაზი",
    ds_ix_bath: "აბაზანა",
    ds_ix_bed: "საწოლი",
    ds_ix_seat: "სავარძელი",
    ds_ix_tv: "ტელევიზორი",
    ds_ix_light: "შუქი",
    ds_ix_lamp: "ლამპა",
    ds_ix_curtain: "ფარდები",
    ds_ix_blind: "ჟალუზი",
    ds_ix_coffee: "ყავის აპარატი",
    ds_ix_recliner: "გადასაწევი სავარძელი",
    ds_ix_mirror: "სარკის შუქი",
    ds_env_title: "დღის დრო",
    "ds_env_DAY": "დღე",
    "ds_env_SUNSET": "მზის ჩასვლა",
    "ds_env_EVENING": "საღამო",
    "ds_env_NIGHT": "ღამე",
    ds_ctrl_title: "როგორ ვიმოძრაოთ",
    ds_ctrl_move: "მოძრაობა",
    ds_ctrl_look: "მიმოხედვა",
    ds_ctrl_mouse: "მაუსი",
    ds_ctrl_click: "დაწკაპუნება",
    ds_ctrl_interact: "მიზნობრივი საგნის გამოყენება",
    ds_ctrl_faster: "უფრო სწრაფი სიარული",
    ds_ctrl_menu: "მენიუ · მაუსის გათავისუფლება",
    ds_ctrl_drag_part: "გადაათრიეთ კარი ან უჯრა ხელით გასახსნელად",
    ds_ctrl_left_thumb: "მარცხენა ცერი",
    ds_ctrl_right_thumb: "მარჯვენა ცერი",
    ds_ctrl_tap: "შეეხეთ საგანს",
    ds_ctrl_got_it: "გასაგებია",
    ds_ctrl_dont_show: "აღარ მაჩვენო",
    ds_ctrl_help: "მართვა",
    ds_ctrl_click_to_look: "დააწკაპუნეთ მაუსით მიმოსახედად",
    ds_menu_title: "შეჩერებულია",
    ds_menu_resume: "გაგრძელება",
    ds_menu_settings: "პარამეტრები",
    ds_set_title: "გავლის პარამეტრები",
    ds_set_look: "მიმოხედვის მგრძნობელობა",
    ds_set_speed: "სიარულის ტემპი",
    ds_set_invert: "ვერტიკალური ხედის შებრუნება",
    ds_set_invert_x: "ჰორიზონტალური ხედის შებრუნება",
    ds_set_reduced: "მოძრაობის შემცირება",
    ds_set_done: "მზადაა",
    ds_walk_seated: "ზიხართ",
    ds_walk_lying: "წევხართ",
    ds_live_title: "იცხოვრე აქ",
    ds_live_intro: "პატარა მომენტები ამ სახლში — იმისგან, რაც მასში ნამდვილად არის.",
    ds_live_coffee: "ყავის მომზადება",
    ds_live_balcony: "დასვენება აივანზე",
    ds_live_tv: "ტელევიზორის ყურება",
    ds_live_kitchen: "სამზარეულოს დათვალიერება",
    ds_live_evening: "საღამო სახლში",
    ds_live_dinner: "ვახშმის მომზადება",
    ds_live_rest: "დასვენება საძინებელში",
    ds_live_step: "ნაბიჯი {{n}} / {{total}}",
    ds_live_walking: "მივდივართ…",
    ds_live_stop: "შეწყვეტა",
    ds_live_finished: "ისიამოვნეთ სახლით.",
    ds_live_none: "ამ სახლში ჯერ არაფერია, რაც ამ მომენტებს ემსახურება.",
    ds_live_blocked: "ეს ადგილი აქედან მიუწვდომელია.",
    ds_ix_washer: "სარეცხი მანქანა",
    ds_walk_tour_play: "გიდიანი ტური",
    ds_walk_tour_pause: "ტურის შეჩერება",
    ds_walk_fullscreen: "სრული ეკრანი",
    share_details: "დიზაინის დეტალები",
    share_whole_home: "მთელი სახლი",
    share_palette: "პალიტრა",
    share_walls: "კედლები",
    share_floor: "იატაკი",
    share_furniture: "ავეჯი",
    share_unchanged: "როგორც აშენებულია",
    share_no_furniture: "ავეჯი არ არის",
    share_walk_room: "ამ ოთახის გავლა",
    share_design_hint: "გადაათრიეთ სახლის შესაბრუნებლად, მასშტაბისთვის გამოიყენეთ ორი თითი ან ბორბალი.",
    share_loading: "გავლა მზადდება…",
    share_brand_line: "შექმნილია HOMATCH Design Studio-ში",
    share_enter: "შიგნით შესვლა",
    share_estimated: "ზომები მიახლოებითია: სივრცე გეგმიდანაა აგებული.",
    share_estimated_pictures: "ზომები მიახლოებითია: სივრცე სურათებიდანაა აღდგენილი.",
    share_preview_note: "დიზაინის წინასწარი ხედი. ფერები, მასალები და განათება რეალობაში შეიძლება განსხვავდებოდეს.",
    share_overview: "მიმოხილვა",
    share_language: "ენა",
    share_revoked_title: "ეს ბმული აღარ არის გაზიარებული",
    share_revoked_body: "მფლობელმა ამ დიზაინის გაზიარება შეწყვიტა. სთხოვეთ ახალი ბმული.",
    share_expired_title: "ამ ბმულს ვადა გაუვიდა",
    share_expired_body: "ბმულები შეიძლება დროებით ზიარდებოდეს. სთხოვეთ მფლობელს ახალი.",
    share_not_found_title: "ეს ბმული არაფერს ხსნის",
    share_not_found_body: "შეამოწმეთ, რომ მთელი ბმული დაკოპირდა.",
    share_unavailable_title: "ამ დიზაინის ჩვენება შეუძლებელია",
    share_unavailable_body: "სივრცე, რომელშიც ის შეიქმნა, აღარ არის ხელმისაწვდომი.",
    share_error_title: "გავლა ვერ ჩაიტვირთა",
    share_error_body: "შეამოწმეთ კავშირი და სცადეთ ხელახლა.",
    share_retry: "ხელახლა ცდა",
    share_webgl: "ამ მოწყობილობას 3D-ის ჩვენება არ შეუძლია."
  },
  ru: {
    ds_room_living: "Гостиная",
    ds_room_bedroom: "Спальня",
    ds_room_kitchen: "Кухня",
    ds_room_bathroom: "Ванная",
    ds_room_wc: "Туалет",
    ds_room_hall: "Прихожая",
    ds_room_corridor: "Коридор",
    ds_room_storage: "Кладовая",
    ds_room_balcony: "Балкон",
    ds_room_terrace: "Терраса",
    ds_room_unknown: "Комната",
    ds_walk_enter: "Пройтись",
    ds_walk_exit: "Выйти",
    ds_walk_title: "Прогулка",
    ds_walk_reset: "К входу",
    ds_walk_rooms: "Перейти в комнату",
    ds_walk_joystick: "Ходьба: потяните, чтобы двигаться",
    ds_walk_help_keys: "W A S D или стрелки — идти · перетаскивание — смотреть · касание или E — открыть · Esc — выйти",
    ds_walk_unavailable: "Для прогулки в этом пространстве не нашлось места, где встать.",
    ds_walk_needs_rooms: "Для прогулки нужны контуры комнат, которых у этого пространства нет.",
    ds_walk_open: "Открыть",
    ds_walk_close: "Закрыть",
    ds_ix_door: "Дверь",
    ds_ix_window: "Окно",
    ds_ix_wardrobe: "Шкаф",
    ds_ix_cabinet: "Шкафчик",
    ds_ix_drawer: "Ящик",
    ds_ix_appliance: "Холодильник",
    ds_walk_photo: "Фото",
    "ds_act_OPEN": "Открыть",
    "ds_act_CLOSE": "Закрыть",
    "ds_act_TURN_ON": "Включить",
    "ds_act_TURN_OFF": "Выключить",
    "ds_act_SIT": "Сесть",
    "ds_act_LIE_DOWN": "Прилечь",
    "ds_act_STAND_UP": "Встать",
    "ds_act_MAKE_BED": "Заправить кровать",
    "ds_act_MESS_BED": "Смять постель",
    "ds_act_FLUSH": "Смыть",
    "ds_act_WASH_HANDS": "Помыть руки",
    "ds_act_MAKE_COFFEE": "Сварить кофе",
    "ds_act_DRINK": "Выпить",
    "ds_act_COOK": "Готовить",
    "ds_act_SERVE": "Подать",
    "ds_act_RECLINE": "Откинуться",
    "ds_act_SIT_UP": "Сесть прямо",
    "ds_act_RUN_BATH": "Набрать ванну",
    "ds_act_DRAIN": "Слить воду",
    "ds_act_RAISE": "Поднять",
    "ds_act_LOWER": "Опустить",
    "ds_act_START": "Запустить",
    ds_ix_balcony_door: "Балконная дверь",
    ds_ix_freezer: "Морозильник",
    ds_ix_oven: "Духовка",
    ds_ix_dishwasher: "Посудомоечная машина",
    ds_ix_stove: "Варочная панель",
    ds_ix_faucet: "Кран",
    ds_ix_shower: "Душ",
    ds_ix_toilet: "Унитаз",
    ds_ix_bath: "Ванна",
    ds_ix_bed: "Кровать",
    ds_ix_seat: "Место",
    ds_ix_tv: "Телевизор",
    ds_ix_light: "Свет",
    ds_ix_lamp: "Лампа",
    ds_ix_curtain: "Шторы",
    ds_ix_blind: "Штора",
    ds_ix_coffee: "Кофемашина",
    ds_ix_recliner: "Кресло-реклайнер",
    ds_ix_mirror: "Подсветка зеркала",
    ds_env_title: "Время суток",
    "ds_env_DAY": "День",
    "ds_env_SUNSET": "Закат",
    "ds_env_EVENING": "Вечер",
    "ds_env_NIGHT": "Ночь",
    ds_ctrl_title: "Как перемещаться",
    ds_ctrl_move: "Идти",
    ds_ctrl_look: "Осмотреться",
    ds_ctrl_mouse: "Мышь",
    ds_ctrl_click: "Клик",
    ds_ctrl_interact: "Взаимодействовать с тем, на что смотрите",
    ds_ctrl_faster: "Идти быстрее",
    ds_ctrl_menu: "Меню · освободить мышь",
    ds_ctrl_drag_part: "Потяните дверь или ящик, чтобы открыть рукой",
    ds_ctrl_left_thumb: "Левый большой палец",
    ds_ctrl_right_thumb: "Правый большой палец",
    ds_ctrl_tap: "Коснитесь предмета",
    ds_ctrl_got_it: "Понятно",
    ds_ctrl_dont_show: "Больше не показывать",
    ds_ctrl_help: "Управление",
    ds_ctrl_click_to_look: "Щёлкните, чтобы осматриваться мышью",
    ds_menu_title: "Пауза",
    ds_menu_resume: "Продолжить",
    ds_menu_settings: "Настройки",
    ds_set_title: "Настройки прогулки",
    ds_set_look: "Чувствительность обзора",
    ds_set_speed: "Темп ходьбы",
    ds_set_invert: "Инвертировать по вертикали",
    ds_set_invert_x: "Инвертировать по горизонтали",
    ds_set_reduced: "Уменьшить движение",
    ds_set_done: "Готово",
    ds_walk_seated: "Вы сидите",
    ds_walk_lying: "Вы лежите",
    ds_live_title: "Пожить здесь",
    ds_live_intro: "Маленькие моменты в этом доме — из того, что в нём действительно есть.",
    ds_live_coffee: "Сварить кофе",
    ds_live_balcony: "Отдохнуть на балконе",
    ds_live_tv: "Посмотреть телевизор",
    ds_live_kitchen: "Осмотреть кухню",
    ds_live_evening: "Вечер дома",
    ds_live_dinner: "Приготовить ужин",
    ds_live_rest: "Отдохнуть в спальне",
    ds_live_step: "Шаг {{n}} из {{total}}",
    ds_live_walking: "Идём туда…",
    ds_live_stop: "Остановить",
    ds_live_finished: "Наслаждайтесь домом.",
    ds_live_none: "В этом доме пока нет ничего для таких моментов.",
    ds_live_blocked: "Туда отсюда не пройти.",
    ds_ix_washer: "Стиральная машина",
    ds_walk_tour_play: "Экскурсия",
    ds_walk_tour_pause: "Пауза",
    ds_walk_fullscreen: "Во весь экран",
    share_details: "Детали дизайна",
    share_whole_home: "Весь дом",
    share_palette: "Палитра",
    share_walls: "Стены",
    share_floor: "Пол",
    share_furniture: "Мебель",
    share_unchanged: "Как построено",
    share_no_furniture: "Мебели нет",
    share_walk_room: "Пройтись по комнате",
    share_design_hint: "Перетаскивайте, чтобы повернуть дом; масштаб — щипком или колёсиком.",
    share_loading: "Готовим прогулку…",
    share_brand_line: "Создано в HOMATCH Design Studio",
    share_enter: "Начать прогулку",
    share_estimated: "Размеры приблизительные: пространство построено по планировке.",
    share_estimated_pictures: "Размеры приблизительные: пространство восстановлено по картинкам.",
    share_preview_note: "Предварительный вид дизайна. В реальности цвета, материалы и свет могут выглядеть иначе.",
    share_overview: "Общий вид",
    share_language: "Язык",
    share_revoked_title: "Эта ссылка больше не действует",
    share_revoked_body: "Владелец больше не делится этим дизайном. Попросите у него новую ссылку.",
    share_expired_title: "Срок действия ссылки истёк",
    share_expired_body: "Ссылки могут действовать ограниченное время. Попросите у владельца новую.",
    share_not_found_title: "Эта ссылка ничего не открывает",
    share_not_found_body: "Проверьте, что ссылка скопирована полностью.",
    share_unavailable_title: "Этот дизайн нельзя показать",
    share_unavailable_body: "Пространство, в котором он создан, больше недоступно.",
    share_error_title: "Не удалось загрузить прогулку",
    share_error_body: "Проверьте соединение и попробуйте снова.",
    share_retry: "Попробовать снова",
    share_webgl: "Это устройство не может показать 3D."
  },
  tr: {
    ds_room_living: "Oturma odası",
    ds_room_bedroom: "Yatak odası",
    ds_room_kitchen: "Mutfak",
    ds_room_bathroom: "Banyo",
    ds_room_wc: "Tuvalet",
    ds_room_hall: "Hol",
    ds_room_corridor: "Koridor",
    ds_room_storage: "Depo",
    ds_room_balcony: "Balkon",
    ds_room_terrace: "Teras",
    ds_room_unknown: "Oda",
    ds_walk_enter: "İçinde dolaş",
    ds_walk_exit: "Dolaşmadan çık",
    ds_walk_title: "İç gezinti",
    ds_walk_reset: "Girişe dön",
    ds_walk_rooms: "Bir odaya git",
    ds_walk_joystick: "Yürü: hareket etmek için sürükleyin",
    ds_walk_help_keys: "Yürümek için W A S D veya oklar · bakmak için sürükleyin · açmak için dokunun veya E · çıkmak için Esc",
    ds_walk_unavailable: "İç gezinti bu alanda durulacak bir yer bulamadı.",
    ds_walk_needs_rooms: "İçinde dolaşmak oda sınırlarını gerektirir; bu alanda bunlar yok.",
    ds_walk_open: "Aç",
    ds_walk_close: "Kapat",
    ds_ix_door: "Kapı",
    ds_ix_window: "Pencere",
    ds_ix_wardrobe: "Gardırop",
    ds_ix_cabinet: "Dolap",
    ds_ix_drawer: "Çekmece",
    ds_ix_appliance: "Buzdolabı",
    ds_walk_photo: "Fotoğraf",
    "ds_act_OPEN": "Aç",
    "ds_act_CLOSE": "Kapat",
    "ds_act_TURN_ON": "Aç",
    "ds_act_TURN_OFF": "Kapat",
    "ds_act_SIT": "Otur",
    "ds_act_LIE_DOWN": "Uzan",
    "ds_act_STAND_UP": "Kalk",
    "ds_act_MAKE_BED": "Yatağı topla",
    "ds_act_MESS_BED": "Yatağı dağıt",
    "ds_act_FLUSH": "Sifonu çek",
    "ds_act_WASH_HANDS": "Elleri yıka",
    "ds_act_MAKE_COFFEE": "Kahve yap",
    "ds_act_DRINK": "İç",
    "ds_act_COOK": "Pişir",
    "ds_act_SERVE": "Servis et",
    "ds_act_RECLINE": "Arkana yaslan",
    "ds_act_SIT_UP": "Doğrul",
    "ds_act_RUN_BATH": "Küveti doldur",
    "ds_act_DRAIN": "Suyu boşalt",
    "ds_act_RAISE": "Kaldır",
    "ds_act_LOWER": "İndir",
    "ds_act_START": "Başlat",
    ds_ix_balcony_door: "Balkon kapısı",
    ds_ix_freezer: "Dondurucu",
    ds_ix_oven: "Fırın",
    ds_ix_dishwasher: "Bulaşık makinesi",
    ds_ix_stove: "Ocak",
    ds_ix_faucet: "Musluk",
    ds_ix_shower: "Duş",
    ds_ix_toilet: "Klozet",
    ds_ix_bath: "Küvet",
    ds_ix_bed: "Yatak",
    ds_ix_seat: "Oturak",
    ds_ix_tv: "Televizyon",
    ds_ix_light: "Işık",
    ds_ix_lamp: "Lamba",
    ds_ix_curtain: "Perdeler",
    ds_ix_blind: "Stor",
    ds_ix_coffee: "Kahve makinesi",
    ds_ix_recliner: "Yatar koltuk",
    ds_ix_mirror: "Ayna ışığı",
    ds_env_title: "Günün saati",
    "ds_env_DAY": "Gündüz",
    "ds_env_SUNSET": "Gün batımı",
    "ds_env_EVENING": "Akşam",
    "ds_env_NIGHT": "Gece",
    ds_ctrl_title: "Nasıl gezinilir",
    ds_ctrl_move: "Yürü",
    ds_ctrl_look: "Etrafa bak",
    ds_ctrl_mouse: "Fare",
    ds_ctrl_click: "Tıkla",
    ds_ctrl_interact: "Baktığın şeyi kullan",
    ds_ctrl_faster: "Daha hızlı yürü",
    ds_ctrl_menu: "Menü · fareyi serbest bırak",
    ds_ctrl_drag_part: "Bir kapıyı veya çekmeceyi elle açmak için sürükleyin",
    ds_ctrl_left_thumb: "Sol başparmak",
    ds_ctrl_right_thumb: "Sağ başparmak",
    ds_ctrl_tap: "Bir nesneye dokunun",
    ds_ctrl_got_it: "Anladım",
    ds_ctrl_dont_show: "Bir daha gösterme",
    ds_ctrl_help: "Kontroller",
    ds_ctrl_click_to_look: "Fareyle etrafa bakmak için tıklayın",
    ds_menu_title: "Duraklatıldı",
    ds_menu_resume: "Devam et",
    ds_menu_settings: "Ayarlar",
    ds_set_title: "İç gezinti ayarları",
    ds_set_look: "Bakış hassasiyeti",
    ds_set_speed: "Yürüme hızı",
    ds_set_invert: "Dikey bakışı ters çevir",
    ds_set_invert_x: "Yatay bakışı ters çevir",
    ds_set_reduced: "Hareketi azalt",
    ds_set_done: "Tamam",
    ds_walk_seated: "Oturuyorsunuz",
    ds_walk_lying: "Uzanıyorsunuz",
    ds_live_title: "Burada yaşa",
    ds_live_intro: "Bu evde, gerçekten içinde olanlarla küçük anlar.",
    ds_live_coffee: "Bir kahve yap",
    ds_live_balcony: "Balkonda dinlen",
    ds_live_tv: "Televizyon izle",
    ds_live_kitchen: "Mutfağı keşfet",
    ds_live_evening: "Evde bir akşam",
    ds_live_dinner: "Akşam yemeği pişir",
    ds_live_rest: "Yatak odasında dinlen",
    ds_live_step: "Adım {{n}} / {{total}}",
    ds_live_walking: "Oraya yürünüyor…",
    ds_live_stop: "Durdur",
    ds_live_finished: "Evin tadını çıkarın.",
    ds_live_none: "Bu evde henüz bu anlar için bir şey yok.",
    ds_live_blocked: "Oraya buradan ulaşılamıyor.",
    ds_ix_washer: "Çamaşır makinesi",
    ds_walk_tour_play: "Rehberli tur",
    ds_walk_tour_pause: "Turu duraklat",
    ds_walk_fullscreen: "Tam ekran",
    share_details: "Tasarım ayrıntıları",
    share_whole_home: "Tüm ev",
    share_palette: "Palet",
    share_walls: "Duvarlar",
    share_floor: "Zemin",
    share_furniture: "Mobilya",
    share_unchanged: "Yapıldığı gibi",
    share_no_furniture: "Mobilya yerleştirilmedi",
    share_walk_room: "Bu odayı gez",
    share_design_hint: "Evi döndürmek için sürükleyin; yakınlaştırmak için iki parmak veya tekerlek.",
    share_loading: "İç gezinti hazırlanıyor…",
    share_brand_line: "HOMATCH Design Studio'da tasarlandı",
    share_enter: "İç gezintiye başla",
    share_estimated: "Ölçüler yaklaşıktır: bu alan bir kat planından oluşturuldu.",
    share_estimated_pictures: "Ölçüler yaklaşıktır: bu alan görsellerden yeniden oluşturuldu.",
    share_preview_note: "Bir tasarım önizlemesi. Renkler, malzemeler ve ışık gerçekte farklı görünebilir.",
    share_overview: "Genel görünüm",
    share_language: "Dil",
    share_revoked_title: "Bu bağlantı artık paylaşılmıyor",
    share_revoked_body: "Sahibi bu tasarımı paylaşmayı bıraktı. Yeni bir bağlantı isteyin.",
    share_expired_title: "Bu bağlantının süresi doldu",
    share_expired_body: "Bağlantılar sınırlı bir süre paylaşılabilir. Sahibinden yenisini isteyin.",
    share_not_found_title: "Bu bağlantı hiçbir şey açmıyor",
    share_not_found_body: "Bağlantının tamamının kopyalandığını kontrol edin.",
    share_unavailable_title: "Bu tasarım gösterilemiyor",
    share_unavailable_body: "Tasarımın yapıldığı alan artık mevcut değil.",
    share_error_title: "İç gezinti yüklenemedi",
    share_error_body: "Bağlantınızı kontrol edip tekrar deneyin.",
    share_retry: "Tekrar dene",
    share_webgl: "Bu cihaz 3B gösteremiyor."
  },
  ar: {
    ds_room_living: "غرفة المعيشة",
    ds_room_bedroom: "غرفة النوم",
    ds_room_kitchen: "المطبخ",
    ds_room_bathroom: "الحمّام",
    ds_room_wc: "دورة المياه",
    ds_room_hall: "الردهة",
    ds_room_corridor: "الممر",
    ds_room_storage: "المخزن",
    ds_room_balcony: "الشرفة",
    ds_room_terrace: "التراس",
    ds_room_unknown: "غرفة",
    ds_walk_enter: "تجوّل في الداخل",
    ds_walk_exit: "إنهاء الجولة",
    ds_walk_title: "جولة داخلية",
    ds_walk_reset: "العودة إلى المدخل",
    ds_walk_rooms: "الانتقال إلى غرفة",
    ds_walk_joystick: "المشي: اسحب للتحرك",
    ds_walk_help_keys: "W A S D أو الأسهم للمشي · اسحب للنظر · المس أو E للفتح · Esc للخروج",
    ds_walk_unavailable: "لم تجد الجولة مكانًا للوقوف في هذه المساحة.",
    ds_walk_needs_rooms: "يتطلب التجوّل مخططات الغرف، وهي غير متوفرة لهذه المساحة.",
    ds_walk_open: "فتح",
    ds_walk_close: "إغلاق",
    ds_ix_door: "باب",
    ds_ix_window: "نافذة",
    ds_ix_wardrobe: "خزانة ملابس",
    ds_ix_cabinet: "خزانة",
    ds_ix_drawer: "درج",
    ds_ix_appliance: "ثلاجة",
    ds_walk_photo: "صورة",
    "ds_act_OPEN": "فتح",
    "ds_act_CLOSE": "إغلاق",
    "ds_act_TURN_ON": "تشغيل",
    "ds_act_TURN_OFF": "إيقاف",
    "ds_act_SIT": "اجلس",
    "ds_act_LIE_DOWN": "استلقِ",
    "ds_act_STAND_UP": "قف",
    "ds_act_MAKE_BED": "رتّب السرير",
    "ds_act_MESS_BED": "بعثر السرير",
    "ds_act_FLUSH": "اسحب السيفون",
    "ds_act_WASH_HANDS": "اغسل يديك",
    "ds_act_MAKE_COFFEE": "حضّر القهوة",
    "ds_act_DRINK": "اشرب",
    "ds_act_COOK": "اطبخ",
    "ds_act_SERVE": "قدّم",
    "ds_act_RECLINE": "أرجِع المقعد",
    "ds_act_SIT_UP": "اعتدل",
    "ds_act_RUN_BATH": "املأ الحوض",
    "ds_act_DRAIN": "فرّغ الماء",
    "ds_act_RAISE": "ارفع",
    "ds_act_LOWER": "أنزل",
    "ds_act_START": "ابدأ",
    ds_ix_balcony_door: "باب الشرفة",
    ds_ix_freezer: "الفريزر",
    ds_ix_oven: "الفرن",
    ds_ix_dishwasher: "غسالة الصحون",
    ds_ix_stove: "الموقد",
    ds_ix_faucet: "الصنبور",
    ds_ix_shower: "الدش",
    ds_ix_toilet: "المرحاض",
    ds_ix_bath: "حوض الاستحمام",
    ds_ix_bed: "السرير",
    ds_ix_seat: "مقعد",
    ds_ix_tv: "التلفاز",
    ds_ix_light: "الضوء",
    ds_ix_lamp: "المصباح",
    ds_ix_curtain: "الستائر",
    ds_ix_blind: "الستارة",
    ds_ix_coffee: "آلة القهوة",
    ds_ix_recliner: "كرسي قابل للإمالة",
    ds_ix_mirror: "إضاءة المرآة",
    ds_env_title: "وقت اليوم",
    "ds_env_DAY": "نهار",
    "ds_env_SUNSET": "الغروب",
    "ds_env_EVENING": "مساء",
    "ds_env_NIGHT": "ليل",
    ds_ctrl_title: "كيف تتنقّل",
    ds_ctrl_move: "تحرّك",
    ds_ctrl_look: "انظر حولك",
    ds_ctrl_mouse: "الفأرة",
    ds_ctrl_click: "انقر",
    ds_ctrl_interact: "استخدم ما تشير إليه",
    ds_ctrl_faster: "امشِ أسرع",
    ds_ctrl_menu: "القائمة · حرّر الفأرة",
    ds_ctrl_drag_part: "اسحب بابًا أو درجًا لفتحه بيدك",
    ds_ctrl_left_thumb: "الإبهام الأيسر",
    ds_ctrl_right_thumb: "الإبهام الأيمن",
    ds_ctrl_tap: "المس شيئًا",
    ds_ctrl_got_it: "فهمت",
    ds_ctrl_dont_show: "لا تعرض مرة أخرى",
    ds_ctrl_help: "التحكم",
    ds_ctrl_click_to_look: "انقر للنظر حولك بالفأرة",
    ds_menu_title: "متوقف مؤقتًا",
    ds_menu_resume: "متابعة",
    ds_menu_settings: "الإعدادات",
    ds_set_title: "إعدادات الجولة",
    ds_set_look: "حساسية النظر",
    ds_set_speed: "سرعة المشي",
    ds_set_invert: "اعكس النظر العمودي",
    ds_set_invert_x: "اعكس النظر الأفقي",
    ds_set_reduced: "تقليل الحركة",
    ds_set_done: "تم",
    ds_walk_seated: "أنت جالس",
    ds_walk_lying: "أنت مستلقٍ",
    ds_live_title: "عِش هنا",
    ds_live_intro: "لحظات صغيرة في هذا المنزل، مما يوجد فيه فعلًا.",
    ds_live_coffee: "حضّر قهوة",
    ds_live_balcony: "استرخِ في الشرفة",
    ds_live_tv: "شاهد التلفاز",
    ds_live_kitchen: "استكشف المطبخ",
    ds_live_evening: "مساء في البيت",
    ds_live_dinner: "اطبخ العشاء",
    ds_live_rest: "استرح في غرفة النوم",
    ds_live_step: "الخطوة {{n}} من {{total}}",
    ds_live_walking: "في الطريق…",
    ds_live_stop: "إيقاف",
    ds_live_finished: "استمتع بالمنزل.",
    ds_live_none: "لا يوجد في هذا المنزل بعد ما يدعم هذه اللحظات.",
    ds_live_blocked: "لا يمكن الوصول إلى هناك من هنا.",
    ds_ix_washer: "الغسالة",
    ds_walk_tour_play: "جولة موجّهة",
    ds_walk_tour_pause: "إيقاف الجولة مؤقتًا",
    ds_walk_fullscreen: "ملء الشاشة",
    share_details: "تفاصيل التصميم",
    share_whole_home: "المنزل كله",
    share_palette: "لوحة الألوان",
    share_walls: "الجدران",
    share_floor: "الأرضية",
    share_furniture: "الأثاث",
    share_unchanged: "كما هو مبني",
    share_no_furniture: "لا يوجد أثاث",
    share_walk_room: "تجوّل في هذه الغرفة",
    share_design_hint: "اسحب لتدوير المنزل، واستخدم إصبعين أو عجلة الفأرة للتكبير.",
    share_loading: "جارٍ تجهيز الجولة…",
    share_brand_line: "صُمّم في HOMATCH Design Studio",
    share_enter: "ابدأ الجولة",
    share_estimated: "الأحجام تقريبية: بُنيت هذه المساحة من مخطط.",
    share_estimated_pictures: "الأحجام تقريبية: أُعيد بناء هذه المساحة من الصور.",
    share_preview_note: "معاينة للتصميم. قد تبدو الألوان والمواد والإضاءة مختلفة في الواقع.",
    share_overview: "نظرة عامة",
    share_language: "اللغة",
    share_revoked_title: "لم يعد هذا الرابط متاحًا",
    share_revoked_body: "توقف المالك عن مشاركة هذا التصميم. اطلب منه رابطًا جديدًا.",
    share_expired_title: "انتهت صلاحية هذا الرابط",
    share_expired_body: "قد تُشارَك الروابط لفترة محدودة. اطلب من المالك رابطًا جديدًا.",
    share_not_found_title: "هذا الرابط لا يفتح شيئًا",
    share_not_found_body: "تأكد من نسخ الرابط كاملًا.",
    share_unavailable_title: "لا يمكن عرض هذا التصميم",
    share_unavailable_body: "لم تعد المساحة التي صُمّم فيها متاحة.",
    share_error_title: "تعذّر تحميل الجولة",
    share_error_body: "تحقّق من اتصالك وحاول مجددًا.",
    share_retry: "أعد المحاولة",
    share_webgl: "لا يستطيع هذا الجهاز عرض المحتوى ثلاثي الأبعاد."
  },
  he: {
    ds_room_living: "סלון",
    ds_room_bedroom: "חדר שינה",
    ds_room_kitchen: "מטבח",
    ds_room_bathroom: "חדר רחצה",
    ds_room_wc: "שירותים",
    ds_room_hall: "מבואה",
    ds_room_corridor: "מסדרון",
    ds_room_storage: "מחסן",
    ds_room_balcony: "מרפסת",
    ds_room_terrace: "מרפסת גג",
    ds_room_unknown: "חדר",
    ds_walk_enter: "סיור פנימי",
    ds_walk_exit: "יציאה מהסיור",
    ds_walk_title: "סיור",
    ds_walk_reset: "חזרה לכניסה",
    ds_walk_rooms: "מעבר לחדר",
    ds_walk_joystick: "הליכה: גררו כדי לזוז",
    ds_walk_help_keys: "W A S D או חיצים להליכה · גררו כדי להסתכל · הקישו או E כדי לפתוח · Esc ליציאה",
    ds_walk_unavailable: "הסיור לא מצא מקום לעמוד בו במרחב הזה.",
    ds_walk_needs_rooms: "סיור פנימי דורש קווי מתאר של חדרים, ולמרחב הזה אין כאלה.",
    ds_walk_open: "פתיחה",
    ds_walk_close: "סגירה",
    ds_ix_door: "דלת",
    ds_ix_window: "חלון",
    ds_ix_wardrobe: "ארון בגדים",
    ds_ix_cabinet: "ארונית",
    ds_ix_drawer: "מגירה",
    ds_ix_appliance: "מקרר",
    ds_walk_photo: "צילום",
    "ds_act_OPEN": "פתיחה",
    "ds_act_CLOSE": "סגירה",
    "ds_act_TURN_ON": "הדלקה",
    "ds_act_TURN_OFF": "כיבוי",
    "ds_act_SIT": "לשבת",
    "ds_act_LIE_DOWN": "לשכב",
    "ds_act_STAND_UP": "לקום",
    "ds_act_MAKE_BED": "לסדר את המיטה",
    "ds_act_MESS_BED": "לפרוע את המיטה",
    "ds_act_FLUSH": "הורדת מים",
    "ds_act_WASH_HANDS": "לשטוף ידיים",
    "ds_act_MAKE_COFFEE": "להכין קפה",
    "ds_act_DRINK": "לשתות",
    "ds_act_COOK": "לבשל",
    "ds_act_SERVE": "להגיש",
    "ds_act_RECLINE": "להשעין לאחור",
    "ds_act_SIT_UP": "להזדקף",
    "ds_act_RUN_BATH": "למלא אמבטיה",
    "ds_act_DRAIN": "לרוקן",
    "ds_act_RAISE": "להרים",
    "ds_act_LOWER": "להוריד",
    "ds_act_START": "להפעיל",
    ds_ix_balcony_door: "דלת מרפסת",
    ds_ix_freezer: "מקפיא",
    ds_ix_oven: "תנור",
    ds_ix_dishwasher: "מדיח כלים",
    ds_ix_stove: "כיריים",
    ds_ix_faucet: "ברז",
    ds_ix_shower: "מקלחת",
    ds_ix_toilet: "אסלה",
    ds_ix_bath: "אמבטיה",
    ds_ix_bed: "מיטה",
    ds_ix_seat: "מושב",
    ds_ix_tv: "טלוויזיה",
    ds_ix_light: "אור",
    ds_ix_lamp: "מנורה",
    ds_ix_curtain: "וילונות",
    ds_ix_blind: "תריס",
    ds_ix_coffee: "מכונת קפה",
    ds_ix_recliner: "כורסת טלוויזיה",
    ds_ix_mirror: "תאורת מראה",
    ds_env_title: "שעה ביום",
    "ds_env_DAY": "יום",
    "ds_env_SUNSET": "שקיעה",
    "ds_env_EVENING": "ערב",
    "ds_env_NIGHT": "לילה",
    ds_ctrl_title: "איך לזוז",
    ds_ctrl_move: "תנועה",
    ds_ctrl_look: "להסתכל סביב",
    ds_ctrl_mouse: "עכבר",
    ds_ctrl_click: "לחיצה",
    ds_ctrl_interact: "להשתמש במה שמולך",
    ds_ctrl_faster: "ללכת מהר יותר",
    ds_ctrl_menu: "תפריט · שחרור העכבר",
    ds_ctrl_drag_part: "גררו דלת או מגירה כדי לפתוח ביד",
    ds_ctrl_left_thumb: "אגודל שמאל",
    ds_ctrl_right_thumb: "אגודל ימין",
    ds_ctrl_tap: "הקישו על חפץ",
    ds_ctrl_got_it: "הבנתי",
    ds_ctrl_dont_show: "לא להציג שוב",
    ds_ctrl_help: "שליטה",
    ds_ctrl_click_to_look: "לחצו כדי להסתכל סביב עם העכבר",
    ds_menu_title: "מושהה",
    ds_menu_resume: "להמשיך",
    ds_menu_settings: "הגדרות",
    ds_set_title: "הגדרות הסיור",
    ds_set_look: "רגישות מבט",
    ds_set_speed: "קצב הליכה",
    ds_set_invert: "היפוך מבט אנכי",
    ds_set_invert_x: "היפוך מבט אופקי",
    ds_set_reduced: "הפחתת תנועה",
    ds_set_done: "סיום",
    ds_walk_seated: "יושבים",
    ds_walk_lying: "שוכבים",
    ds_live_title: "לגור כאן",
    ds_live_intro: "רגעים קטנים בבית הזה, ממה שבאמת נמצא בו.",
    ds_live_coffee: "להכין קפה",
    ds_live_balcony: "להירגע במרפסת",
    ds_live_tv: "לראות טלוויזיה",
    ds_live_kitchen: "לחקור את המטבח",
    ds_live_evening: "ערב בבית",
    ds_live_dinner: "לבשל ארוחת ערב",
    ds_live_rest: "לנוח בחדר השינה",
    ds_live_step: "שלב {{n}} מתוך {{total}}",
    ds_live_walking: "הולכים לשם…",
    ds_live_stop: "עצירה",
    ds_live_finished: "תיהנו מהבית.",
    ds_live_none: "עדיין אין בבית הזה משהו שתומך ברגעים האלה.",
    ds_live_blocked: "אי אפשר להגיע לשם מכאן.",
    ds_ix_washer: "מכונת כביסה",
    ds_walk_tour_play: "סיור מודרך",
    ds_walk_tour_pause: "השהיית הסיור",
    ds_walk_fullscreen: "מסך מלא",
    share_details: "פרטי העיצוב",
    share_whole_home: "כל הבית",
    share_palette: "פלטה",
    share_walls: "קירות",
    share_floor: "רצפה",
    share_furniture: "רהיטים",
    share_unchanged: "כפי שנבנה",
    share_no_furniture: "לא הוצבו רהיטים",
    share_walk_room: "סיור בחדר הזה",
    share_design_hint: "גררו כדי לסובב את הבית; צבטו או גללו כדי להתקרב.",
    share_loading: "מכינים את הסיור…",
    share_brand_line: "עוצב ב־HOMATCH Design Studio",
    share_enter: "כניסה לסיור",
    share_estimated: "המידות משוערות: המרחב נבנה מתוכנית קומה.",
    share_estimated_pictures: "המידות משוערות: המרחב שוחזר מתמונות.",
    share_preview_note: "תצוגה מקדימה של עיצוב. צבעים, חומרים ותאורה עשויים להיראות אחרת במציאות.",
    share_overview: "מבט כללי",
    share_language: "שפה",
    share_revoked_title: "הקישור הזה כבר לא משותף",
    share_revoked_body: "הבעלים הפסיקו לשתף את העיצוב הזה. בקשו מהם קישור חדש.",
    share_expired_title: "תוקף הקישור פג",
    share_expired_body: "אפשר לשתף קישורים לזמן מוגבל. בקשו מהבעלים קישור חדש.",
    share_not_found_title: "הקישור הזה לא פותח דבר",
    share_not_found_body: "בדקו שכל הקישור הועתק.",
    share_unavailable_title: "אי אפשר להציג את העיצוב הזה",
    share_unavailable_body: "המרחב שבו הוא נוצר כבר אינו זמין.",
    share_error_title: "לא ניתן היה לטעון את הסיור",
    share_error_body: "בדקו את החיבור ונסו שוב.",
    share_retry: "נסו שוב",
    share_webgl: "המכשיר הזה לא יכול להציג תלת־ממד."
  }
};
