import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://tas.ge/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(1).click();
  const page1 = await page1Promise;
  await page1.getByRole('textbox', { name: 'ძიება' }).click();
  await page1.getByRole('textbox', { name: 'ძიება' }).press('ControlOrMeta+ვ');
  await page1.getByRole('textbox', { name: 'ძიება' }).fill('01.18.06.019.055.03.01.603');
  await page1.getByText('01.18.06.019.055').click();
  await page1.locator('mat-tree-node:nth-child(10) > .app-tree-node-wrapper > .mat-icon > svg').click();
  await page1.getByRole('treeitem', { name: 'რეგისტრირებული მიწის ნაკვეთები' }).getByLabel('').check();
  await page1.getByRole('treeitem', { name: 'სისტემური რეგისტრაცია-საველე სამუშაოების მონაცემები' }).getByLabel('').check();
  await page1.locator('mat-tree-node:nth-child(7) > .app-tree-node-wrapper > .mat-icon > svg > #arrow_drop_down_black_24dp > #Path_5884').click();
  await page1.locator('mat-tree-node:nth-child(11) > .app-tree-node-wrapper > .mat-icon > svg').click();
  await page1.locator('mat-tree-node:nth-child(18) > .app-tree-node-wrapper > .mat-icon > svg').click();
  await page1.locator('#mat-mdc-checkbox-12-input').check();
  await page1.locator('#mat-mdc-checkbox-13-input').check();
  await page1.locator('mat-tree-node:nth-child(26) > .app-tree-node-wrapper > .mat-icon > svg').click();
  await page1.locator('#mat-mdc-checkbox-14-input').check();
  await page1.locator('#mat-mdc-checkbox-15-input').check();
  await page1.locator('mat-tree-node:nth-child(30) > .app-tree-node-wrapper > .mat-icon > svg').click();
  await page1.locator('#mat-mdc-checkbox-17-input').check();
  await page1.locator('#mat-mdc-checkbox-18-input').check();
  await page1.locator('#mat-mdc-checkbox-19-input').check();
  await page1.getByRole('treeitem', { name: 'თბილისის ელექტრონული განცხადებები' }).locator('svg').click();
  await page1.getByRole('treeitem', { name: 'არქიტექტურული საკითხები' }).getByLabel('').check();
  await page1.getByRole('treeitem', { name: 'ურბანული საკითხები' }).getByLabel('').check();
  await page1.getByRole('treeitem', { name: 'სატრანსპორტო საკითხები' }).getByLabel('').check();
  await page1.getByRole('treeitem', { name: 'მუნიციპალური ინსპექცია' }).getByLabel('').check();
  await page1.locator('mat-tree-node:nth-child(6) > .app-tree-node-wrapper > .mat-icon > svg').click();
  await page1.locator('mat-tree-node:nth-child(15) > .app-tree-node-wrapper > .mat-icon > svg').click();
  await page1.locator('#mat-mdc-checkbox-32-input').check();
  await page1.getByRole('img', { name: 'info icon' }).click();
  await page1.locator('app-ol-map canvas').click({
    position: {
      x: 624,
      y: 260
    }
  });
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('row', { name: 'საჯარო რეესტრის ინფორმაცია:' }).getByRole('link').click();
  const page2 = await page2Promise;
  const page3Promise = page2.waitForEvent('popup');
  await page2.locator('[id="35713848"]').getByRole('cell', { name: 'რეგისტრაციის თარიღი: 14/07/' }).click();
  const page3 = await page3Promise;
  await page1.locator('div').filter({ hasText: 'ინფორმაცია' }).nth(3).click();
  await page1.locator('app-info-result-window').getByText('მშენებლობის ნებართვები').click();
  const page4Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR11101896' }).getByRole('link').click();
  const page4 = await page4Promise;
  const page5Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR11084312' }).getByRole('link').click();
  const page5 = await page5Promise;
  const page6Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR1990786' }).getByRole('link').click();
  const page6 = await page6Promise;
  const page7Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR1968595' }).getByRole('link').click();
  const page7 = await page7Promise;
  const page8Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR1942605' }).getByRole('link').click();
  const page8 = await page8Promise;
  const page9Promise = page1.waitForEvent('popup');
  await page1.locator('div:nth-child(7) > .app-result-tbl-div > .app-result-tbl > tr:nth-child(2) > .app-dynamic-field-value-div > div > a').click();
  const page9 = await page9Promise;
  await page1.locator('app-info-result-window').getByText('I').click();
  const page10Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR11115640' }).getByRole('link').click();
  const page10 = await page10Promise;
  const page11Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR1761052' }).getByRole('link').click();
  const page11 = await page11Promise;
  await page1.locator('app-info-result-window').getByText('სამართლებრივი საკითხები').click();
  const page12Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR11148112' }).getByRole('link').click();
  const page12 = await page12Promise;
  const page13Promise = page12.waitForEvent('popup');
  await page12.locator('iframe').contentFrame().locator('#gridview-1051').click();
  const page13 = await page13Promise;
  const page14Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR11031305' }).getByRole('link').click();
  const page14 = await page14Promise;
  const page15Promise = page14.waitForEvent('popup');
  await page14.locator('iframe').contentFrame().locator('#gridview-1051').click();
  const page15 = await page15Promise;
  const page16Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR11026464' }).getByRole('link').click();
  const page16 = await page16Promise;
  const page17Promise = page16.waitForEvent('popup');
  await page16.locator('iframe').contentFrame().locator('#gridview-1051').click();
  const page17 = await page17Promise;
  await page1.locator('app-info-result-window').getByText('მიწის ნაკვეთის გამოყენების პირობები').click();
  const page18Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR1897963' }).getByRole('link').click();
  const page18 = await page18Promise;
  const page19Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR1850793' }).getByRole('link').click();
  const page19 = await page19Promise;
  const page20Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR1850369' }).getByRole('link').click();
  const page20 = await page20Promise;
  const page21Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR1668968' }).getByRole('link').click();
  const page21 = await page21Promise;
  const page22Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'განცხადების ნომერი:AR1639208' }).getByRole('link').click();
  const page22 = await page22Promise;
  await page1.locator('app-info-result-window').getByText('საგზაო მოძრაობის ორგანიზების სქემები').click();
  const page23Promise = page1.waitForEvent('popup');
  await page1.getByRole('table').filter({ hasText: 'ინფო:დოკუმენტის ნომერი:01242571792-16' }).getByRole('link').click();
  const page23 = await page23Promise;
  await page1.locator('app-info-result-window').getByText('სპეციალური /ზონალური/შეთანხმება').click();
  await page1.locator('app-info-result-window').getByText('შენობა - ნაგებობები (არქივი').click();
  await page1.locator('app-info-result-window').getByText('გზათა ქსელი (თბილისი)').click();
  await page1.locator('app-info-result-window').getByText('საქართველოს რეგიონული საზღვარი').click();
  await page1.locator('app-info-result-window').getByText('რეგისტრირებული მიწის ნაკვეთები').click();
});