import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,'Content-Type':'application/json'}});
const DEMAND=new Set(['BUY','RENT','INVEST','RELOCATE_BUY','RELOCATE_RENT']);

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});
 const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
 try{
  const {batchSize=300,market='GE'}=await req.json().catch(()=>({}));
  const {data:signals,error}=await db.from('raw_signals').select(`id,original_text,language,platform,source:source_registry!source_id(country_code,language)`).eq('classification_status','PENDING').order('discovered_at',{ascending:true}).limit(Math.min(500,batchSize));
  if(error)throw error;if(!signals?.length)return json({success:true,processed:0,classified:0,filteredOut:0,errors:0});
  const key=Deno.env.get('OPENAI_API_KEY')!;if(!key)return json({error:'OPENAI_API_KEY missing'},500);
  let classified=0,filteredOut=0,errors=0,totalCostUsd=0;
  for(let i=0;i<signals.length;i+=20){const chunk=signals.slice(i,i+20);try{
    const prompt=`You are Homatch's strict multilingual real-estate DEMAND classifier. Decide whether each public post expresses the author's CURRENT DEMAND for real estate, not supply. DEMAND means the author wants to BUY, RENT/LEASE, INVEST IN, or relocate and acquire/rent property. SUPPLY means an owner/agent/developer is OFFERING, SELLING, RENTING OUT, advertising or listing property. A normal listing such as 'Apartment for Rent', 'For Sale', price/area/address/features, agent marketing, developer promotion MUST NOT be classified as RENT or BUY demand. Also reject news, jobs, utilities, proxy posts, unrelated content and vague mentions. Property can be ANY type: apartment, house, villa, land, plot, agricultural land, office, retail, warehouse, hotel, commercial space, development site, building, studio, penthouse, townhouse or other. Return JSON object {"results":[...]} with one result per supplied id. Each result: {"id":string,"intentType":"BUY|RENT|INVEST|RELOCATE_BUY|RELOCATE_RENT|SELLER|AGENT_AD|PROPERTY_AD|SPAM|NOISE|UNKNOWN","country":string|null,"region":string|null,"city":string|null,"district":string|null,"neighborhoods":string[]|null,"transactionType":"SALE|RENT|INVESTMENT"|null,"propertyTypes":string[]|null,"bedroomsMin":number|null,"bedroomsMax":number|null,"areaMin":number|null,"areaMax":number|null,"budgetMin":number|null,"budgetMax":number|null,"currency":string|null,"timeline":string|null,"relocationIntent":boolean,"investmentIntent":boolean,"language":string|null,"intentConfidence":number,"specificityScore":number,"actionabilityScore":number,"translatedText":string|null}. Never invent unknown values. If it is a property advertisement, classify PROPERTY_AD/AGENT_AD even if the words buy/rent appear.`;
    const input=chunk.map((s:any)=>({id:s.id,text:String(s.original_text||'').slice(0,2500),language:s.language||null,platform:s.platform}));
    const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-4o-mini',temperature:0,response_format:{type:'json_object'},messages:[{role:'system',content:prompt},{role:'user',content:JSON.stringify(input)}]})});
    if(!r.ok)throw new Error(`OpenAI ${r.status}: ${(await r.text()).slice(0,300)}`);const raw=await r.json();const u=raw.usage||{};totalCostUsd+=(Number(u.prompt_tokens||0)*0.15+Number(u.completion_tokens||0)*0.6)/1_000_000;
    let parsed:any={};try{parsed=JSON.parse(raw.choices?.[0]?.message?.content||'{}')}catch{}const byId=new Map((parsed.results||[]).map((x:any)=>[x.id,x]));
    for(const s of chunk){const x:any=byId.get(s.id);if(!x){await db.from('raw_signals').update({classification_status:'ERROR'}).eq('id',s.id);errors++;continue}const isDemand=DEMAND.has(x.intentType)&&Number(x.intentConfidence||0)>=0.25;if(!isDemand){await db.from('raw_signals').update({classification_status:'FILTERED_OUT',intent_type:x.intentType||null,intent_json:x}).eq('id',s.id);filteredOut++;continue}const source=Array.isArray(s.source)?s.source[0]:s.source;const {error:ins}=await db.from('intent_profiles').insert({signal_id:s.id,intent_type:x.intentType,country:x.country||source?.country_code||market,region:x.region||null,city:x.city||null,district:x.district||null,neighborhoods:x.neighborhoods||null,transaction_type:x.transactionType||null,property_types:x.propertyTypes||null,bedrooms_min:x.bedroomsMin||null,bedrooms_max:x.bedroomsMax||null,area_min:x.areaMin||null,area_max:x.areaMax||null,budget_min:x.budgetMin||null,budget_max:x.budgetMax||null,currency:x.currency||null,timeline:x.timeline||null,relocation_intent:!!x.relocationIntent,investment_intent:!!x.investmentIntent,language:x.language||s.language||source?.language||null,intent_confidence:Number(x.intentConfidence||0),specificity_score:Number(x.specificityScore||0),actionability_score:Number(x.actionabilityScore||0),original_text:s.original_text,translated_text:x.translatedText||null,ai_model:'gpt-4o-mini',ai_cost_usd:Math.max(0.00001,totalCostUsd/Math.max(1,signals.length))});if(ins){await db.from('raw_signals').update({classification_status:'ERROR'}).eq('id',s.id);errors++;}else{await db.from('raw_signals').update({classification_status:'CLASSIFIED',intent_type:x.intentType,intent_json:x}).eq('id',s.id);classified++;}}
  }catch(e){console.error('classification chunk',e);for(const s of chunk){await db.from('raw_signals').update({classification_status:'ERROR'}).eq('id',s.id);errors++;}}}
  if(totalCostUsd>0)await db.from('cost_events').insert({provider:'OPENAI',operation_type:'CLASSIFY_SIGNALS_V2',market,units:signals.length,cost_usd:totalCostUsd,success:errors<signals.length,cache_hit:false});
  return json({success:true,processed:signals.length,classified,filteredOut,errors,totalCostUsd});
 }catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}
});
