import React, { useEffect, useState } from 'react';
import type { BrowsePage, ResultFilters } from '@/services/marketplaceSearch';
import { SELLER_KEY } from './PropertyCard';
import type { T } from './format';
const CONTROL = 'h-11 w-full min-w-0 rounded-xl border border-border bg-background px-3 text-sm text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--gold))]';
export function ResultFiltersPanel({ t, filters, facets, onChange, onReset }: { t: T; filters: ResultFilters; facets: BrowsePage['facets']; onChange: (patch: Partial<ResultFilters>) => void; onReset: () => void }) {
  const active = Object.entries(filters).filter(([key]) => key !== 'sort' && key !== 'section').length;
  const [draft, setDraft] = useState<ResultFilters>(filters);
  const filterKey = JSON.stringify(filters);
  useEffect(() => setDraft(filters), [filterKey]);
  useEffect(() => {
    const delta: Partial<ResultFilters> = {};
    for (const key of ['priceMin', 'priceMax', 'areaMin', 'areaMax', 'bedroomsMin', 'roomsMin'] as const) if (draft[key] !== filters[key]) delta[key] = draft[key];
    if (!Object.keys(delta).length) return;
    const timer = window.setTimeout(() => onChange(delta), 400);
    return () => window.clearTimeout(timer);
  }, [JSON.stringify(draft), filterKey]);
  const number = (key: 'priceMin' | 'priceMax' | 'areaMin' | 'areaMax' | 'bedroomsMin' | 'roomsMin', label: string) => <label key={key} className="min-w-0 space-y-1"><span className="block text-xs text-muted-foreground">{t(label)}</span><input className={CONTROL} type="number" min="0" inputMode="decimal" value={draft[key] ?? ''} onChange={(e) => setDraft((d) => ({ ...d, [key]: e.target.value === '' ? undefined : Math.max(0, Number(e.target.value)) }))} /></label>;
  const select = (key: keyof ResultFilters, label: string, options: Array<[string, string]>) => <label key={key} className="min-w-0 space-y-1"><span className="block text-xs text-muted-foreground">{t(label)}</span><select className={CONTROL} value={String(filters[key] ?? '')} onChange={(e) => onChange({ [key]: e.target.value || undefined })}><option value="">{t('fpr_any')}</option>{options.map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select></label>;
  return <div className="hm-discovery-panel p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold">{t('fpr_filters')}{active ? ` · ${active}` : ''}</p><div className="flex flex-wrap items-center gap-2"><label className="flex min-w-0 items-center gap-2 text-xs text-muted-foreground"><span>{t('fpr_sort')}</span><select aria-label={t('fpr_sort')} className={`${CONTROL} !w-auto max-w-[13rem]`} value={filters.sort ?? 'RANKED'} onChange={(e) => onChange({ sort: e.target.value as ResultFilters['sort'] })}>{['RANKED', 'FRESHEST', 'PRICE', 'VALUE'].map((value) => <option key={value} value={value}>{t(`fpr_sort_${value}`)}</option>)}</select></label><button type="button" onClick={onReset} disabled={!active && !filters.section && (!filters.sort || filters.sort === 'RANKED')} className="min-h-[44px] rounded-xl px-3 text-xs font-semibold text-foreground disabled:opacity-40">{t('fpr_clear')}</button></div></div>
    <details className="mt-2" open={active > 0 || undefined}><summary className="min-h-[44px] cursor-pointer py-3 text-sm text-muted-foreground">{t('fpr_refine')}</summary><div className="grid grid-cols-2 gap-3 pt-2 md:grid-cols-3 xl:grid-cols-4">{number('priceMin', 'fpr_price_min')}{number('priceMax', 'fpr_price_max')}{number('areaMin', 'fpr_area_min')}{number('areaMax', 'fpr_area_max')}{number('bedroomsMin', 'fpr_bedrooms_min')}{number('roomsMin', 'fpr_rooms_min')}
      {facets.districts.length > 1 ? select('district', 'fpr_location', facets.districts.map((v) => [v, v])) : null}{select('ageDays', 'fpr_age', [['1', t('fpr_day')], ['7', t('fpr_week')], ['30', t('fpr_month')]])}{facets.buildings.length ? select('building', 'mps_req_buildingStatus', facets.buildings.map((v) => [v, t(`mps_bs_${v}`)])) : null}{facets.conditions.length ? select('condition', 'fpr_condition', facets.conditions.map((v) => [v, t(`mps_rn_${v}`)])) : null}{facets.sellers.length > 1 ? select('seller', 'fpr_seller', facets.sellers.map((v) => [v, t(SELLER_KEY[v])])) : null}{facets.sources.length > 1 ? select('source', 'fpr_source', facets.sources.map((v) => [v.key, v.name])) : null}{select('verification', 'fpr_verification', [['CLEAR', t('fpr_clear_evidence')], ['NEEDS', t('fpr_needs_evidence')]])}
    </div><div className="mt-4 flex flex-wrap gap-4 text-sm">{(['strongOnly', 'hidePossibleDuplicates'] as const).map((key) => <label key={key} className="flex min-h-[44px] cursor-pointer items-center gap-2"><input type="checkbox" checked={!!filters[key]} onChange={(e) => onChange({ [key]: e.target.checked || undefined })} className="h-4 w-4 accent-[hsl(var(--gold))]" />{t(`fpr_${key}`)}</label>)}</div></details>
    {active ? <ul className="mt-3 flex flex-wrap gap-2" aria-label={t('fpr_active_filters')}>{Object.entries(filters).filter(([key]) => key !== 'sort' && key !== 'section').map(([key, value]) => <li key={key}><button type="button" onClick={() => onChange({ [key]: undefined })} className="min-h-[44px] rounded-xl border border-[hsl(var(--gold)/0.4)] bg-[hsl(var(--gold)/0.06)] px-3 text-xs">{t(`fpr_filter_${key}`)}{typeof value !== 'boolean' ? `: ${key === 'seller' ? t(SELLER_KEY[String(value)]) : key === 'building' ? t(`mps_bs_${value}`) : key === 'condition' ? t(`mps_rn_${value}`) : key === 'verification' ? t(value === 'CLEAR' ? 'fpr_clear_evidence' : 'fpr_needs_evidence') : value}` : ''} <span aria-hidden="true">×</span></button></li>)}</ul> : null}
  </div>;
}
