import React from 'react';
import { Link } from 'react-router-dom';
import { HomatchLogo } from '@/components/common/HomatchLogo';
import { FileText } from 'lucide-react';

const LAST_UPDATED = 'August 28, 2026';

interface SectionProps {
  title: string;
  children: React.ReactNode;
}

function Section({ title, children }: SectionProps) {
  return (
    <section className="space-y-3">
      <h2 className="text-base font-semibold text-foreground">{title}</h2>
      <div className="text-sm text-muted-foreground leading-relaxed space-y-2">
        {children}
      </div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      {/* ── Nav ──────────────────────────────────────────────── */}
      <header className="border-b border-border/50 px-4 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link to="/">
            <HomatchLogo size="sm" />
          </Link>
          <Link
            to="/privacy"
            className="text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            Privacy Policy →
          </Link>
        </div>
      </header>

      {/* ── Content ──────────────────────────────────────────── */}
      <main className="flex-1 px-4 py-12">
        <div className="max-w-3xl mx-auto space-y-10">
          {/* Header */}
          <div className="space-y-3">
            <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-lg border border-border bg-secondary">
              <FileText className="h-3.5 w-3.5 text-primary" />
              <span className="text-xs font-semibold text-primary uppercase tracking-wide">Terms of Service</span>
            </div>
            <h1 className="text-2xl md:text-3xl font-semibold text-foreground text-balance">
              Homatch Terms of Service
            </h1>
            <p className="text-sm text-muted-foreground">
              Last updated: {LAST_UPDATED}
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Please read these Terms of Service ("Terms") carefully before using the Homatch website
              at{' '}
              <a href="https://homatch.live" className="text-primary hover:underline">
                homatch.live
              </a>{' '}
              and the Homatch AI property-matching service (collectively, the "Service") operated by
              Homatch ("we", "us", or "our"). By accessing or using the Service, you agree to be
              bound by these Terms. If you do not agree, do not use the Service.
            </p>
          </div>

          <div className="w-full h-px bg-border/50" />

          <Section title="1. Acceptance of Terms">
            <p>
              By creating an account or using the Service in any way, you confirm that you are at
              least 16 years of age, have the legal capacity to enter into a binding agreement, and
              agree to comply with these Terms and our{' '}
              <Link to="/privacy" className="text-primary hover:underline">
                Privacy Policy
              </Link>
              , which is incorporated herein by reference.
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              Homatch is an AI-powered property-matching platform that analyses property listings
              (submitted via URL or manual entry) and searches public online sources to identify
              potential buyers, tenants, or investors who may be interested in the property. Match
              results are surfaced as signals with a quality score; full contact details are
              unlocked by spending credits.
            </p>
            <p>
              The Service is provided on an "as-is" and "as-available" basis. Match results are
              generated by AI and are indicative only. We do not guarantee the accuracy,
              completeness, or suitability of any match result for any particular purpose.
            </p>
          </Section>

          <Section title="3. User Accounts">
            <p>
              You must create an account to use the full Service. You are responsible for maintaining
              the confidentiality of your account credentials and for all activity that occurs under
              your account. You agree to notify us immediately at{' '}
              <a href="mailto:support@homatch.live" className="text-primary hover:underline">
                support@homatch.live
              </a>{' '}
              if you suspect unauthorised access to your account.
            </p>
            <p>
              You may not create an account on behalf of another person without their express
              permission, impersonate any person or entity, or use the Service for any unlawful
              purpose.
            </p>
          </Section>

          <Section title="4. Credits and Payments">
            <p>
              Accessing full match details requires spending credits. Credits are purchased through
              our payment processor (Stripe) and are non-refundable unless otherwise required by
              applicable law. Credit balances do not expire.
            </p>
            <p>
              Prices are displayed in USD and are subject to change. We will provide reasonable
              notice of price changes. All purchases are final once processed.
            </p>
          </Section>

          <Section title="5. Acceptable Use">
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1.5 mt-2">
              <li>Use the Service to spam, harass, or contact individuals without a legitimate basis</li>
              <li>Scrape, copy, or redistribute match data beyond your own business use</li>
              <li>Use automated tools to submit bulk property URLs beyond normal usage patterns</li>
              <li>Attempt to reverse-engineer, decompile, or circumvent any security feature of the Service</li>
              <li>Use the Service in violation of any applicable law, including data protection and anti-spam laws</li>
              <li>Misrepresent your identity or the nature of a property listing</li>
              <li>Transmit viruses, malware, or any other harmful code</li>
            </ul>
            <p className="mt-3">
              We reserve the right to suspend or terminate accounts that violate these rules without
              prior notice.
            </p>
          </Section>

          <Section title="6. Intellectual Property">
            <p>
              The Service, including its design, code, algorithms, branding, and content (excluding
              user-submitted content), is owned by Homatch and is protected by applicable intellectual
              property laws. You may not reproduce, distribute, or create derivative works from our
              content without prior written permission.
            </p>
            <p>
              You retain ownership of any property data or content you submit to the Service. By
              submitting content, you grant us a limited, non-exclusive licence to use it solely to
              provide the Service.
            </p>
          </Section>

          <Section title="7. Data and Privacy">
            <p>
              Our collection and use of personal data is governed by our{' '}
              <Link to="/privacy" className="text-primary hover:underline">
                Privacy Policy
              </Link>
              . By using the Service, you consent to our data practices as described therein. Match
              signals are sourced from publicly available online content; we do not access private
              messages or non-public data.
            </p>
          </Section>

          <Section title="8. Third-Party Services">
            <p>
              The Service integrates with third-party providers including Google (authentication),
              Stripe (payments), and OpenAI (AI processing). Your use of these integrations is also
              subject to those providers' terms of service and privacy policies. We are not
              responsible for the practices of any third-party provider.
            </p>
          </Section>

          <Section title="9. Disclaimers">
            <p>
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
              PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE
              UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.
            </p>
            <p>
              MATCH RESULTS ARE GENERATED BY AI AND ARE FOR INFORMATIONAL PURPOSES ONLY. HOMATCH
              MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THE ACCURACY OF ANY MATCH OR THE
              INTENTIONS OF ANY INDIVIDUAL IDENTIFIED IN A MATCH RESULT.
            </p>
          </Section>

          <Section title="10. Limitation of Liability">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HOMATCH AND ITS OFFICERS,
              EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, GOODWILL, OR
              BUSINESS OPPORTUNITIES, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.
            </p>
            <p>
              OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING FROM THESE TERMS OR THE SERVICE
              SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.
            </p>
          </Section>

          <Section title="11. Indemnification">
            <p>
              You agree to indemnify and hold harmless Homatch and its affiliates, officers,
              employees, and agents from any claims, damages, losses, or expenses (including
              reasonable legal fees) arising from your use of the Service, your violation of these
              Terms, or your infringement of any third-party rights.
            </p>
          </Section>

          <Section title="12. Termination">
            <p>
              We may suspend or terminate your access to the Service at any time, with or without
              cause, with or without notice. You may delete your account at any time by contacting
              us at{' '}
              <a href="mailto:support@homatch.live" className="text-primary hover:underline">
                support@homatch.live
              </a>
              . Upon termination, your right to use the Service ceases immediately. Unused credits
              are non-refundable unless required by law.
            </p>
          </Section>

          <Section title="13. Governing Law">
            <p>
              These Terms shall be governed by and construed in accordance with applicable law.
              Any dispute arising from or related to these Terms shall first be addressed through
              good-faith negotiation. If unresolved, disputes shall be submitted to binding
              arbitration or the courts of competent jurisdiction.
            </p>
          </Section>

          <Section title="14. Changes to Terms">
            <p>
              We reserve the right to modify these Terms at any time. Material changes will be
              communicated by updating the "Last updated" date and, where appropriate, by email
              notification. Your continued use of the Service after changes take effect constitutes
              your acceptance of the revised Terms.
            </p>
          </Section>

          <Section title="15. Contact">
            <p>
              For questions about these Terms, please contact us:
            </p>
            <div className="mt-2 p-4 rounded-xl border border-border bg-card space-y-1">
              <p className="font-medium text-foreground">Homatch</p>
              <p>
                Email:{' '}
                <a href="mailto:legal@homatch.live" className="text-primary hover:underline">
                  legal@homatch.live
                </a>
              </p>
              <p>
                Website:{' '}
                <a href="https://homatch.live" className="text-primary hover:underline">
                  homatch.live
                </a>
              </p>
            </div>
          </Section>
        </div>
      </main>

      {/* ── Footer ───────────────────────────────────────────── */}
      <footer className="border-t border-border/50 px-4 py-5">
        <div className="max-w-3xl mx-auto flex flex-col md:flex-row items-center justify-between gap-2">
          <HomatchLogo size="sm" />
          <div className="flex items-center gap-4">
            <Link to="/privacy" className="text-xs text-muted-foreground/60 hover:text-muted-foreground transition-colors">Privacy Policy</Link>
            <Link to="/terms" className="text-xs text-primary">Terms of Service</Link>
          </div>
          <p className="text-xs text-muted-foreground/50">
            © {new Date().getFullYear()} Homatch. AI Property Matching.
          </p>
        </div>
      </footer>
    </div>
  );
}
