import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AppLayout } from '@/components/layouts/AppLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Search, Shield, Loader2, ExternalLink, Building2, MapPin, AlertTriangle, Bot } from 'lucide-react';
import { supabase } from '@/db/supabase';
import { useAuth } from '@/contexts/AuthContext';
import { useLanguage } from '@/contexts/LanguageContext';
import { HumanVerificationBrowser } from '@/components/research/HumanVerificationBrowser';

type Mode='property'|'cadastral';
type Source={label:string;url?:string;evidenceLevel?:string;excerpt?:string};
type Report={status?:string;queryType:string;entityName?:string;entityType?:string;entityConfidence?:string;confidence:number;summary:string;confidenceBreakdown?:{project?:string;publicEvidence?:number;exactUnit?:number};identifiedParent?:{code?:string;name?:string;address?:string;developer?:string;confidence?:string}|null;exactUnit?:{code?:string;verified?:boolean;verificationLevel?:string;address?:string;areaSqm?:number;note?:string};building?:{name?:string;address?:string;developer?:string;floors?:number;status?:string;units?:number;areaRange?:string;amenities?:string[]}|null;market?:{currentListings?:string[];historicalListings?:string[];priceEvidence?:string[]}|null;officialEvidence?:string[];publicEvidence?:string[];conflicts?:string[];unverified?:string[];sources?:Source[];requiresManualVerification?:boolean;manualVerificationUrl?:string;warnings?:string[]};

const clean=(s?:string)=>String(s||'').replace(/\*\*/g,'').replace(/#{1,6}\s*/g,'').replace(/\[([^\]]+)\]\([^\)]+\)/g,'$1').replace(/```[\s\S]*?```/g,'').trim();
const list=(title:string,items?:string[])=>items?.length?<Card><CardHeader className="pb-2"><CardTitle className="text-sm">{title}</CardTitle></CardHeader><CardContent className="space-y-2">{items.slice(0,8).map((x,i)=><div key={i} className="text-xs text-muted-foreground leading-relaxed">• {clean(x)}</div>)}</CardContent></Card>:null;

export default function VerifyPage(){
 const nav=useNavigate(); const {session}=useAuth(); const {lang}=useLanguage();
 const [mode,setMode]=useState<Mode>('property'); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(false); const [report,setReport]=useState<Report|null>(null); const [err,setErr]=useState<string|null>(null); const [verifiedTick,setVerifiedTick]=useState(0);
 const valid=mode==='cadastral'?/^\d{1,6}(\.\d{1,6}){3,11}$/.test(query.trim()):query.trim().length>=2;
 const run=async()=>{if(!valid)return;setLoading(true);setErr(null);setReport(null);try{const {data,error}=await supabase.functions.invoke('homatch-research',{body:{query:query.trim(),type:mode,userId:session?.user?.id,language:lang,verificationCompleted:verifiedTick>0}});if(error)throw error;if(data?.error)throw new Error(data.error);setReport(data)}catch(e:any){setErr(e?.message||'კვლევა ვერ შესრულდა')}finally{setLoading(false)}};
 return <AppLayout><div className="max-w-4xl mx-auto space-y-5 pb-16">
  <div><div className="flex items-center gap-2"><Shield className="h-6 w-6 text-primary"/><h1 className="text-2xl font-bold">გადამოწმების ცენტრი</h1></div><p className="text-sm text-muted-foreground mt-1">მოძებნეთ ქონება სახელით, მისამართით, პროექტით ან საკადასტრო კოდით. Homatch აერთიანებს საჯარო კვლევას და საჭიროებისას ოფიციალურ live verification-ს.</p></div>
  <Tabs value={mode} onValueChange={v=>{setMode(v as Mode);setReport(null);setErr(null);setQuery('')}}><TabsList className="grid grid-cols-2 w-full"><TabsTrigger value="property">ქონება / სახელი / მისამართი</TabsTrigger><TabsTrigger value="cadastral">საკადასტრო კოდი</TabsTrigger></TabsList></Tabs>
  <Card><CardContent className="pt-5"><div className="flex gap-2"><Input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&valid&&run()} placeholder={mode==='property'?'მაგ: Villion Krtsanisi Homes, Krtsanisi 6, Millennio Group...':'მაგ: 01.18.06.019.055.03.01.803'} className="font-medium"/><Button onClick={run} disabled={!valid||loading}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<><Search className="h-4 w-4 mr-2"/>ძიება</>}</Button></div><p className="text-xs text-muted-foreground mt-2">{mode==='property'?'შეგიძლიათ ჩაწეროთ პროექტის/დეველოპერის სახელი, მისამართი ან სხვა აღწერითი ინფორმაცია.':'საკადასტრო ძიება დამატებით ამოწმებს parent parcel-ს და ოფიციალურ წყაროებს.'}</p></CardContent></Card>
  {err&&<div className="p-4 rounded-xl border border-destructive/30 bg-destructive/10 text-sm text-destructive">{err}</div>}
  {loading&&<div className="py-12 text-center"><Loader2 className="h-8 w-8 animate-spin mx-auto text-primary"/><p className="text-sm text-muted-foreground mt-3">Homatch ეძებს რამდენიმე დამოუკიდებელ საჯარო და ოფიციალურ წყაროში…</p></div>}
  {report&&!loading&&<div className="space-y-4">
   <Card><CardContent className="pt-5 space-y-3"><div className="flex items-center gap-2 flex-wrap"><h2 className="text-lg font-semibold">{clean(report.entityName)||query}</h2><Badge variant="outline">{report.entityType||mode}</Badge>{report.entityConfidence&&<Badge variant="outline">Project: {report.entityConfidence}</Badge>}<Badge variant="outline">Public: {report.confidence||0}%</Badge>{mode==='cadastral'&&<Badge variant={report.exactUnit?.verified?'default':'outline'}>Exact unit: {report.exactUnit?.verified?'VERIFIED':'NEEDS OFFICIAL CHECK'}</Badge>}</div><p className="text-sm text-muted-foreground leading-relaxed">{clean(report.summary)}</p></CardContent></Card>
   {report.identifiedParent&&<Card><CardHeader className="pb-2"><CardTitle className="text-sm flex items-center gap-2"><MapPin className="h-4 w-4"/>იდენტიფიცირებული ქონება / Parent parcel</CardTitle></CardHeader><CardContent className="grid sm:grid-cols-2 gap-2 text-sm"><div><span className="text-muted-foreground">კოდი: </span>{report.identifiedParent.code||'—'}</div><div><span className="text-muted-foreground">პროექტი: </span>{report.identifiedParent.name||'—'}</div><div><span className="text-muted-foreground">მისამართი: </span>{report.identifiedParent.address||'—'}</div><div><span className="text-muted-foreground">დეველოპერი: </span>{report.identifiedParent.developer||'—'}</div></CardContent></Card>}
   {report.building&&<Card><CardHeader className="pb-2"><CardTitle className="text-sm flex items-center gap-2"><Building2 className="h-4 w-4"/>შენობა / პროექტი</CardTitle></CardHeader><CardContent className="grid sm:grid-cols-2 gap-2 text-sm">{report.building.address&&<div><span className="text-muted-foreground">მისამართი: </span>{report.building.address}</div>}{report.building.developer&&<div><span className="text-muted-foreground">დეველოპერი: </span>{report.building.developer}</div>}{report.building.floors&&<div><span className="text-muted-foreground">სართულები: </span>{report.building.floors}</div>}{report.building.units&&<div><span className="text-muted-foreground">ერთეულები: </span>{report.building.units}</div>}{report.building.status&&<div><span className="text-muted-foreground">სტატუსი: </span>{report.building.status}</div>}{report.building.areaRange&&<div><span className="text-muted-foreground">ფართობები: </span>{report.building.areaRange}</div>}</CardContent></Card>}
   {list('ოფიციალური მტკიცებულებები',report.officialEvidence)}{list('საჯარო მტკიცებულებები',report.publicEvidence)}{list('ფასები / ბაზრის მტკიცებულებები',report.market?.priceEvidence)}
   {!!report.conflicts?.length&&<Card className="border-amber-500/25"><CardHeader className="pb-2"><CardTitle className="text-sm flex gap-2"><AlertTriangle className="h-4 w-4 text-amber-400"/>შეუსაბამობები</CardTitle></CardHeader><CardContent>{report.conflicts.map((x,i)=><p key={i} className="text-xs text-muted-foreground mb-2">• {clean(x)}</p>)}</CardContent></Card>}
   {!!report.sources?.length&&<Card><CardHeader className="pb-2"><CardTitle className="text-sm">წყაროები</CardTitle></CardHeader><CardContent className="space-y-2">{report.sources.slice(0,12).map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-3 p-2 rounded-lg border border-border hover:border-primary/40"><div className="min-w-0"><p className="text-xs font-medium truncate">{clean(s.label)}</p><p className="text-[10px] text-muted-foreground">{s.evidenceLevel||'WEB'}</p></div><ExternalLink className="h-3.5 w-3.5 shrink-0"/></a>)}</CardContent></Card>}
   {mode==='cadastral'&&report.requiresManualVerification&&<HumanVerificationBrowser cadastralCode={query.trim()} targetUrl={report.manualVerificationUrl||'https://slr.napr.gov.ge/slr/index/measured'} onVerified={async()=>{setVerifiedTick(x=>x+1);await run()}}/>}
   <Button variant="outline" onClick={()=>nav('/ai',{state:{prompt:`გააანალიზე გადამოწმების შედეგი: ${query}`,context:{type:'verify',data:report}}})}><Bot className="h-4 w-4 mr-2"/>Homatch AI-ს კითხვა</Button>
  </div>}
 </div></AppLayout>
}