import test from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import {readFile,writeFile,mkdir} from 'node:fs/promises';
// Emit only the modules excluded from the normal test build, then execute
// the actual production orchestrator. No loader, browser or external request.
const config=JSON.parse(await readFile(new URL('../tsconfig.test.json',import.meta.url),'utf8'));
for(const file of config.exclude.filter(file=>file.endsWith('.ts')&&!file.endsWith('index.ts'))){const input=new URL('../'+file,import.meta.url);const output=new URL('../.tstest-build/'+file.replace(/^src\//,'').replace(/\.ts$/,'.js'),import.meta.url);await mkdir(new URL('.',output),{recursive:true});await writeFile(output,ts.transpileModule(await readFile(input,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText);}
const {ResearchOrchestrator}=await import('../.tstest-build/orchestrator/ResearchOrchestrator.js');
const response=value=>new Response(JSON.stringify(value));
test('real orchestrator runStep dispatches API before acquiring browser context, keep=false',async()=>{const original=globalThis.fetch;const orchestrator=new ResearchOrchestrator();try{globalThis.fetch=async(url)=>response(String(url).endsWith('/api/search')?{applist:[{appID:'runtime-id',regNumber:'runtime-reg'}],page:1,lastpage:1,total:1}:{status:10});const job={id:'api-dispatch-test',query:'runtime-code',mode:'cadastral'};const browser=new Proxy({}, {get(){throw new Error('Service176 accessed the browser');}});const step=await orchestrator.runStep(browser,job,{type:'source',key:'mygov'});assert.equal(step.keep,false);assert.equal(step.result.status,'BLOCKED');assert.equal(step.result.traversal.continuations[0].recordId,'runtime-id');assert.equal(orchestrator.getSession(job.id),undefined);}finally{globalThis.fetch=original;}});
test('real run loop continues to the next provider and completes after gated My.gov',async()=>{const original=globalThis.fetch;const orchestrator=new ResearchOrchestrator();const invoked=[];try{globalThis.fetch=async(url)=>response(String(url).endsWith('/api/search')?{applist:[{appID:'runtime-id',regNumber:'runtime-reg'}],page:1,lastpage:1,total:1}:{status:15});const originalStep=orchestrator.runStep.bind(orchestrator);orchestrator.runStep=async(browser,job,step)=>{invoked.push(step.key);if(step.key==='mygov')return originalStep(browser,job,step);return{keep:false,result:{source:step.key,status:'NO_RESULT_CONFIRMED',resultConfirmed:false,noResultConfirmed:true,documents:[]}};};const job={id:'nonblocking-run-test',query:'runtime-code',mode:'cadastral',status:'QUEUED',stage:'QUEUED',sourceIndex:0,results:[],steps:[{type:'source',key:'mygov'},{type:'source',key:'tas'}],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};orchestrator.jobs.set(job.id,job);await orchestrator.run(job,0,{closed:true});assert.deepEqual(invoked,['mygov','tas']);assert.equal(job.status,'COMPLETE');assert.equal(job.results[0].status,'BLOCKED');assert.equal(job.results[0].resultConfirmed,false);assert.equal(job.humanVerification,undefined);assert.equal(orchestrator.getSession(job.id),undefined);assert.equal(job.results[1].source,'tas');}finally{globalThis.fetch=original;}});
