import React, { useState } from 'react';
import { ShieldCheck, Loader2, ExternalLink, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { supabase } from '@/db/supabase';
interface Props { cadastralCode?: string; targetUrl?: string; onVerified?: () => void | Promise<void> }
export function HumanVerificationBrowser({ cadastralCode, targetUrl, onVerified }: Props) {
 const [loading,setLoading]=useState(false); const [liveViewUrl,setLiveViewUrl]=useState<string|null>(null); const [officialUrl,setOfficialUrl]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [status,setStatus]=useState<string|null>(null);
 const openVerification=async()=>{setLoading(true);setError(null);try{const {data,error:ie}=await supabase.functions.invoke('browserbase-handoff',{body:{cadastralCode,targetUrl}});if(ie)throw ie;if(!data?.liveViewUrl)throw new Error(data?.error||'Live browser is unavailable');setLiveViewUrl(data.liveViewUrl);setOfficialUrl(data.targetUrl||targetUrl||null);setStatus(data.navigationStatus||null)}catch(e){setError(e instanceof Error?e.message:'Live browser ვერ გაეშვა')}finally{setLoading(false)}};
 if(liveViewUrl)return <div className="fixed inset-0 z-[100] bg-background flex flex-col"><div className="h-14 border-b border-border px-4 flex items-center gap-3 bg-card"><ShieldCheck className="h-5 w-5 text-primary"/><div className="min-w-0 flex-1"><p className="text-sm font-semibold">ოფიციალური Live Verification</p><p className="text-[11px] text-muted-foreground truncate">Homatch-მა ოფიციალური გვერდი გახსნა და საკადასტრო კოდის შეტანა სცადა. თუ CAPTCHA გამოჩნდა, შეასრულეთ აქვე.</p></div>{officialUrl&&<Button size="sm" variant="outline" onClick={()=>window.open(officialUrl,'_blank','noopener,noreferrer')}><ExternalLink className="h-4 w-4 mr-1"/>ოფიციალური გვერდი</Button>}<Button size="icon" variant="ghost" onClick={()=>setLiveViewUrl(null)}><X className="h-5 w-5"/></Button></div><iframe title="Homatch official verification browser" src={liveViewUrl} className="flex-1 w-full border-0 bg-white" allow="clipboard-read; clipboard-write"/><div className="border-t border-border p-3 bg-card flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground">{status==='SEARCH_SUBMITTED'?'ძიება უკვე გაშვებულია — დაასრულეთ CAPTCHA თუ გამოჩნდა.':status==='CODE_FILLED'?'კოდი უკვე ჩაწერილია — დააჭირეთ ძებნას და გაიარეთ CAPTCHA თუ გამოჩნდა.':'დაასრულეთ ოფიციალური ძიება ამ ფანჯარაში.'}</p><Button onClick={async()=>{setLiveViewUrl(null);await onVerified?.()}}><ShieldCheck className="h-4 w-4 mr-2"/>დავასრულე — გააგრძელე კვლევა</Button></div></div>;
 return <Card className="border-amber-500/25 bg-amber-500/5"><CardContent className="p-4 flex flex-col sm:flex-row gap-3 sm:items-center"><ShieldCheck className="h-5 w-5 text-amber-400 shrink-0"/><div className="flex-1"><p className="text-sm font-medium">ოფიციალური Live Verification</p><p className="text-xs text-muted-foreground mt-0.5">Homatch გახსნის კონტროლირებად cloud browser-ს, გადავა ოფიციალურ საიტზე და საკადასტრო კოდის ჩაწერას/ძიების გაშვებას სცდის. CAPTCHA ავტომატურად არ გადაიჭრება — თუ გამოჩნდა, თქვენ შეასრულებთ Live View-ში.</p>{error&&<p className="text-xs text-destructive mt-1">{error}</p>}</div><Button onClick={openVerification} disabled={loading} variant="outline">{loading?<Loader2 className="h-4 w-4 mr-2 animate-spin"/>:<ShieldCheck className="h-4 w-4 mr-2"/>}გახსენი Live Verification</Button></CardContent></Card>
}