import React,{useCallback,useEffect,useRef,useState}from'react';
import{Loader2,ShieldCheck,X,AlertTriangle,RefreshCw}from'lucide-react';
import{Button}from'@/components/ui/button';import{supabase}from'@/db/supabase';
const WORKER='https://homatch-official-worker-production.up.railway.app';const API_KEY=import.meta.env.VITE_SUPABASE_ANON_KEY;
type Props={open:boolean;jobId?:string;site?:string;onComplete:()=>void|Promise<void>;onClose?:()=>void};type Shot={image:string;width:number;height:number;url?:string;captcha?:boolean;expiresAt?:string};
export function ResearchCaptchaModal({open,jobId,site,onComplete,onClose}:Props){const[shot,setShot]=useState<Shot|null>(null),[busy,setBusy]=useState(false),[err,setErr]=useState<string|null>(null),[finishing,setFinishing]=useState(false);const img=useRef<HTMLImageElement|null>(null);
 const call=useCallback(async(body:any)=>{if(!jobId)throw new Error('Verification session ვერ მოიძებნა');const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('სესია აღარ არის აქტიური');const action=String(body.action||'screenshot');let path=`/research/${jobId}/screenshot`,method='GET',payload:any=undefined;if(action==='input'){path=`/research/${jobId}/action`;method='POST';payload={...body};delete payload.action}else if(action==='resume'){path=`/research/${jobId}/resume`;method='POST';payload={humanVerificationCompleted:true}}const r=await fetch(`${WORKER}${path}`,{method,headers:{Authorization:`Bearer ${session.access_token}`,apikey:API_KEY,'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined});const data=await r.json().catch(()=>({error:`HTTP ${r.status}`}));if(!r.ok||data?.error)throw new Error(data?.error||`HTTP ${r.status}`);return data},[jobId]);
 const refresh=useCallback(async()=>{if(!open||!jobId)return;setBusy(true);setErr(null);try{setShot(await call({action:'screenshot'}))}catch(e:any){setErr(e?.message||'დადასტურების ფანჯარა ვერ ჩაიტვირთა')}finally{setBusy(false)}},[open,jobId,call]);useEffect(()=>{if(open)refresh();else{setShot(null);setErr(null)}},[open,refresh]);const click=async(e:React.MouseEvent<HTMLImageElement>)=>{if(busy||!shot||!img.current)return;const r=img.current.getBoundingClientRect(),x=(e.clientX-r.left)*shot.width/r.width,y=(e.clientY-r.top)*shot.height/r.height;setBusy(true);setErr(null);try{await call({action:'input',type:'click',x,y});await refresh()}catch(e:any){setErr(e?.message||'მოქმედება ვერ შესრულდა');setBusy(false)}};if(!open)return null;
 return <div className="fixed inset-0 z-[120] bg-black/70 backdrop-blur-sm p-4 flex items-center justify-center"><div className="w-full max-w-2xl rounded-2xl border border-border bg-background shadow-2xl overflow-hidden"><div className="px-5 py-4 border-b flex items-center gap-3 bg-card"><ShieldCheck className="h-5 w-5 text-primary"/><div className="flex-1 min-w-0"><p className="text-sm font-semibold">უსაფრთხოების დადასტურება</p><p className="text-xs text-muted-foreground">{site?`${site}: `:''}დაასრულეთ CAPTCHA. დანარჩენ კვლევას Homatch ავტომატურად გააგრძელებს.</p></div><Button size="icon" variant="ghost" onClick={refresh} disabled={busy}><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/></Button>{onClose&&<Button size="icon" variant="ghost" onClick={onClose}><X className="h-4 w-4"/></Button>}</div><div className="relative bg-neutral-950 min-h-[260px] max-h-[560px] overflow-auto grid place-items-center p-2">{busy&&!shot&&<div className="text-center text-white"><Loader2 className="h-7 w-7 animate-spin mx-auto"/><p className="text-xs mt-2">CAPTCHA იტვირთება…</p></div>}{err&&<div className="absolute z-10 top-3 left-3 right-3 p-3 rounded-lg bg-destructive text-destructive-foreground text-xs">{err}</div>}{shot?.image?<img ref={img} src={shot.image} onClick={click} draggable={false} className="max-w-full h-auto cursor-pointer select-none" alt="Human verification"/>:!busy&&<div className="text-center text-white p-8"><AlertTriangle className="h-7 w-7 mx-auto"/><p className="text-sm mt-2">CAPTCHA session ვერ ჩაიტვირთა.</p></div>}</div><div className="px-5 py-4 border-t bg-card flex items-center justify-between gap-4"><p className="text-xs text-muted-foreground">დააჭირეთ CAPTCHA-ს საჭირო ადგილს. საიტის დანარჩენ ნაწილს Homatch background-ში მართავს.</p><Button disabled={finishing||busy||!shot} onClick={async()=>{setFinishing(true);setErr(null);try{await call({action:'resume'});await onComplete()}catch(e:any){setErr(e?.message||'CAPTCHA ჯერ დასრულებული არ არის');await refresh()}finally{setFinishing(false)}}}>{finishing?<Loader2 className="h-4 w-4 animate-spin mr-2"/>:<ShieldCheck className="h-4 w-4 mr-2"/>}დადასტურება დასრულებულია</Button></div></div></div>}
