import express from 'express';
import { chromium } from 'playwright';
import pdf from 'pdf-parse';
const app=express();
const ALLOWED_ORIGINS=new Set(['https://homatch.live','https://www.homatch.live']);
app.use((req,res,next)=>{const origin=String(req.headers.origin||'');if(origin&&(ALLOWED_ORIGINS.has(origin)||/^https:\/\/homatch-[a-z0-9-]+-insportia\.vercel\.app$/i.test(origin))){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin')}res.setHeader('Access-Control-Allow-Headers','authorization,apikey,content-type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});app.use(express.json({limit:'1mb'}));
const PORT=Number(process.env.PORT||3000),TOKEN=process.env.WORKER_TOKEN||'',SUPABASE_URL=process.env.SUPABASE_URL||'';const jobs=new Map(),sessions=new Map(),TTL=15*60*1000;
const SOURCES={tas:{name:'TAS',class:'OFFICIAL_GOVERNMENT',url:'https://tas.ge/?p=searchdocument&menuItemId=7104'},msmap:{name:'MS Cadastral Map',class:'OFFICIAL_GOVERNMENT',url:'https://ms.gov.ge/msmap/#C=44.7433554-41.7850526@Z=19'},mygov:{name:'MY.GOV.GE Property Service',class:'OFFICIAL_GOVERNMENT',url:'https://www.my.gov.ge/ka-ge/services/5/service/176'},enreg:{name:'Entrepreneur Registry',class:'OFFICIAL_REGISTRY',url:'https://enreg.reestri.gov.ge/main.php?m=new_index'},napr:{name:'NAPR',class:'OFFICIAL_REGISTRY',url:'https://napr.gov.ge/'}};const now=()=>new Date().toISOString();
async function auth(req,res,next){const h=String(req.headers.authorization||'');if(TOKEN&&h===`Bearer ${TOKEN}`)return next();if(SUPABASE_URL&&h.startsWith('Bearer ')){try{const k=String(req.headers.apikey||'');if(!k)return res.status(401).json({error:'apikey required'});if((await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{Authorization:h,apikey:k}})).ok)return next()}catch{}}return res.status(401).json({error:'unauthorized'})}
const text=async(p,n=120000)=>{try{return(await p.locator('body').innerText({timeout:10000})).slice(0,n)}catch{return''}};async function visible(x){try{return await x.count()&&await x.isVisible()}catch{return false}}
async function challenge(p){for(const f of p.frames()){for(const s of ['iframe[src*="recaptcha" i]','iframe[src*="hcaptcha" i]','iframe[src*="turnstile" i]','.g-recaptcha','.h-captcha','.cf-turnstile','[class*="captcha" i]','[id*="captcha" i]','[role="checkbox"][aria-label*="robot" i]']){const x=f.locator(s).first();if(await visible(x))return{frame:f,el:x}}const b=(await f.locator('body').innerText().catch(()=>'' )).slice(0,15000).toLowerCase();if(/verify you are human|i am not a robot|i'm not a robot|captcha|მე არ ვარ რობოტი|არ ვარ რობოტი/.test(b)){const x=f.locator('iframe,input,button,[role="checkbox"],[role="dialog"]').first();if(await visible(x))return{frame:f,el:x}}}return null}
async function contexts(p){return [p.mainFrame(),...p.frames().filter(f=>f!==p.mainFrame())]}
async function fillAny(p,q,hints=[]){for(const f of await contexts(p)){for(const s of hints){const x=f.locator(s).first();try{if(await visible(x)){await x.fill(q);if((await x.inputValue().catch(()=>'' )).replace(/\s/g,'')===q.replace(/\s/g,''))return{frame:f,el:x,selector:s}}catch{}}const inputs=f.locator('input:not([type="hidden"]):not([type="checkbox"]):not([type="radio"]),textarea');let n=Math.min(await inputs.count().catch(()=>0),40);for(let i=0;i<n;i++){const x=inputs.nth(i);if(!await visible(x))continue;const m=((await x.getAttribute('placeholder'))+' '+(await x.getAttribute('name'))+' '+(await x.getAttribute('id'))+' '+(await x.getAttribute('aria-label'))).toLowerCase();if(/საკადასტრო|cadast|cadastr|parcel|უძრავ|ძიება|search/.test(m)){try{await x.fill(q);if((await x.inputValue()).replace(/\s/g,'')===q.replace(/\s/g,''))return{frame:f,el:x,selector:m}}catch{}}}}return null}
async function submitNear(p,hit){if(!hit)return false;const f=hit.frame;for(const re of [/მოძებნა/i,/ძიება/i,/search/i,/შემდეგ/i,/დადასტურება/i])for(const role of ['button','link']){const x=f.getByRole(role,{name:re}).first();try{if(await visible(x)){await x.click();await p.waitForTimeout(2000);return true}}catch{}}try{await hit.el.press('Enter');await p.waitForTimeout(2000);return true}catch{}return false}
async function tas(p,q){await p.waitForTimeout(2500);const hit=await fillAny(p,q,['input[placeholder*="საკადასტრო" i]','input[name*="cad" i]','input[id*="cad" i]','input[type="text"]']);if(!hit)return{found:false,submitted:false,adapter:'TAS_FRAME_AWARE'};return{found:true,submitted:await submitNear(p,hit),adapter:'TAS_FRAME_AWARE',frameUrl:hit.frame.url()}}
async function msmap(p,q){await p.waitForTimeout(3000);let hit=await fillAny(p,q,['input[placeholder="ძიება"]','input[placeholder*="ძიება" i]','input[type="search"]']);if(!hit)return{found:false,submitted:false,adapter:'MSMAP_SPA'};return{found:true,submitted:await submitNear(p,hit),adapter:'MSMAP_SPA',frameUrl:hit.frame.url()}}
async function mygov(p,q){await p.waitForTimeout(3000);const hit=await fillAny(p,q,['input[placeholder*="საკადასტრო" i]','input[name*="cad" i]','input[id*="cad" i]','input[type="text"]']);if(!hit)return{found:false,submitted:false,adapter:'MYGOV_SERVICE'};return{found:true,submitted:await submitNear(p,hit),adapter:'MYGOV_SERVICE',frameUrl:hit.frame.url()}}
async function generic(p,q){const hit=await fillAny(p,q);return hit?{found:true,submitted:await submitNear(p,hit),adapter:'GENERIC'}:{found:false,submitted:false,adapter:'GENERIC'}}async function search(p,key,q){if(key==='tas')return tas(p,q);if(key==='msmap')return msmap(p,q);if(key==='mygov')return mygov(p,q);return generic(p,q)}
async function pageLinks(p){const out=[];for(const f of await contexts(p)){try{out.push(...await f.locator('a[href]').evaluateAll(as=>as.slice(0,300).map(a=>({label:(a.textContent||'').trim().slice(0,240),url:a.href})).filter(x=>/^https?:/i.test(x.url))))}catch{}}return [...new Map(out.map(x=>[x.url,x])).values()]}
async function pdfEvidence(p,ls){const docs=[];for(const l of ls.filter(x=>/\.pdf(?:$|\?)|download|document|extract|ამონაწერ|გადმოწერ|დოკუმენტ/i.test(`${x.label} ${x.url}`)).slice(0,12)){try{const r=await p.request.get(l.url,{timeout:20000}),b=await r.body(),ct=(r.headers()['content-type']||'').toLowerCase();if(ct.includes('pdf')||b.subarray(0,4).toString()==='%PDF'){const d=await pdf(b);docs.push({url:l.url,label:l.label,type:'PDF',pages:d.numpages,text:(d.text||'').slice(0,100000),parsed:true})}}catch(e){docs.push({url:l.url,label:l.label,type:'DOCUMENT',parsed:false,error:String(e)})}}return docs}
async function collect(p,key,sr){const src=SOURCES[key],ls=await pageLinks(p),cap=await challenge(p),docs=cap?[]:await pdfEvidence(p,ls),pageText=await text(p),q=(sr?.query||'').replace(/\s/g,''),evidence=!!sr?.submitted&&(pageText.replace(/\s/g,'').includes(q)||docs.some(d=>d.text?.replace(/\s/g,'').includes(q)));return{source:key,sourceName:src.name,sourceClass:src.class,sourceUrl:src.url,finalUrl:p.url(),adapter:sr?.adapter||null,frameUrl:sr?.frameUrl||null,retrievalMethod:sr?.submitted?'OFFICIAL_FORM_RESULT':'NO_VERIFIED_SEARCH',searched:!!sr?.submitted,resultValidated:evidence,status:cap?'WAITING_HUMAN':sr?.submitted?'RESULT_RETRIEVED':'FAILED',captcha:!!cap,retrievedAt:now(),pageText,links:ls,documents:docs,documentLinks:ls.filter(x=>/\.pdf|download|document|ამონაწერ|დოკუმენტ/i.test(`${x.label} ${x.url}`))}}
async function hold(browser,ctx,p,job,key,sr){sessions.set(job.id,{browser,ctx,p,key,query:job.query,sr,expires:Date.now()+TTL});return{r:await collect(p,key,sr),keep:true}}
async function one(browser,job,key){const src=SOURCES[key],ctx=await browser.newContext({locale:'ka-GE',acceptDownloads:true,viewport:{width:1440,height:1000}}),p=await ctx.newPage();try{await p.goto(src.url,{waitUntil:'domcontentloaded',timeout:45000});await p.waitForTimeout(1500);if(await challenge(p))return hold(browser,ctx,p,job,key,{found:false,submitted:false,query:job.query,adapter:`${key.toUpperCase()}_PRESEARCH`});const sr={...(await search(p,key,job.query)),query:job.query};if(await challenge(p))return hold(browser,ctx,p,job,key,sr);const r=await collect(p,key,sr);if(!sr.found)r.error='source adapter could not locate cadastral search control';else if(!sr.submitted)r.error='source adapter could not submit cadastral search';await ctx.close();return{r,keep:false}}catch(e){await ctx.close().catch(()=>{});return{r:{source:key,sourceName:src.name,sourceClass:src.class,sourceUrl:src.url,status:'FAILED',searched:false,resultValidated:false,error:String(e),retrievedAt:now(),pageText:'',links:[],documents:[]},keep:false}}}
async function run(job,start=0,browser=null){const keys=job.mode==='cadastral'?['tas','msmap','mygov','napr']:['enreg','msmap','napr'];job.status='RUNNING';job.updatedAt=now();try{browser=browser||await chromium.launch({headless:true,args:['--disable-dev-shm-usage','--no-sandbox']});for(let i=start;i<keys.length;i++){job.sourceIndex=i;job.stage=`CHECKING_${keys[i].toUpperCase()}`;const {r,keep}=await one(browser,job,keys[i]);job.results=job.results.filter(x=>x.source!==keys[i]);job.results.push(r);job.updatedAt=now();if(keep){job.status='WAITING_HUMAN';job.stage='CAPTCHA_REQUIRED';job.humanVerification={source:keys[i],url:r.finalUrl||r.sourceUrl,expiresAt:new Date(Date.now()+TTL).toISOString(),message:'წყარომ მოითხოვა ადამიანის დადასტურება. დაასრულეთ მხოლოდ ეს შემოწმება; იგივე სესია ავტომატურად გაგრძელდება.'};return}}job.status='COMPLETE';job.stage='COMPLETE';job.completedAt=now();job.officialEvidenceCount=job.results.filter(x=>x.resultValidated).length;await browser.close().catch(()=>{})}catch(e){job.status='FAILED';job.stage='FAILED';job.error=String(e);await browser?.close().catch(()=>{});job.updatedAt=now()}}
setInterval(async()=>{for(const[id,s]of sessions)if(Date.now()>s.expires){await s.ctx.close().catch(()=>{});await s.browser.close().catch(()=>{});sessions.delete(id);const j=jobs.get(id);if(j?.status==='WAITING_HUMAN'){j.status='FAILED';j.stage='HUMAN_SESSION_EXPIRED';j.error='Human verification session expired';j.updatedAt=now()}}},30000).unref();
app.get('/health',(_q,r)=>r.json({ok:true,service:'homatch-official-worker',version:'1.1.0',playwright:true,pdfExtraction:true,sourceAdapters:['tas-frame-aware','msmap-spa','mygov-service'],humanSessionControls:true,evidenceValidation:true}));app.post('/research',auth,(req,res)=>{const mode=req.body?.mode==='property'?'property':'cadastral',query=mode==='cadastral'?String(req.body?.query||'').trim().replace(/\s/g,''):String(req.body?.query||'').trim();if(!query)return res.status(400).json({error:'query required'});const id=crypto.randomUUID(),j={id,query,mode,status:'QUEUED',stage:'QUEUED',sourceIndex:0,results:[],createdAt:now(),updatedAt:now()};jobs.set(id,j);run(j);res.status(202).json({accepted:true,jobId:id,status:j.status})});app.get('/research/:id',auth,(req,res)=>{const j=jobs.get(req.params.id);return j?res.json(j):res.status(404).json({error:'not found'})});
app.get('/research/:id/screenshot',auth,async(req,res)=>{const s=sessions.get(req.params.id);if(!s)return res.status(404).json({error:'active human session not found'});try{const c=await challenge(s.p);if(!c)return res.status(409).json({error:'visible human verification challenge not found'});const img=await s.p.screenshot({type:'jpeg',quality:80});res.json({image:`data:image/jpeg;base64,${img.toString('base64')}`,width:1440,height:1000,offsetX:0,offsetY:0,url:s.p.url(),source:s.key,captcha:true})}catch(e){res.status(500).json({error:String(e)})}});app.post('/research/:id/action',auth,async(req,res)=>{const s=sessions.get(req.params.id);if(!s)return res.status(404).json({error:'active human session not found'});try{if(String(req.body?.type)!=='click')return res.status(400).json({error:'unsupported action'});const x=Number(req.body.x)+Number(req.body.offsetX||0),y=Number(req.body.y)+Number(req.body.offsetY||0);await s.p.mouse.click(x,y);await s.p.waitForTimeout(700);s.expires=Date.now()+TTL;res.json({ok:true,captcha:!!(await challenge(s.p)),url:s.p.url()})}catch(e){res.status(500).json({error:String(e)})}});app.post('/research/:id/resume',auth,async(req,res)=>{const j=jobs.get(req.params.id),s=sessions.get(req.params.id);if(!j||!s)return res.status(404).json({error:'active human session not found'});if(await challenge(s.p))return res.status(409).json({error:'human verification is not complete'});let sr=s.sr;if(!sr?.submitted)sr={...(await search(s.p,s.key,s.query)),query:s.query};if(await challenge(s.p))return res.status(409).json({error:'human verification required after search submission'});if(!sr.submitted)return res.status(422).json({error:'cadastral search could not be submitted after verification'});const r=await collect(s.p,s.key,sr);j.results=j.results.filter(x=>x.source!==s.key);j.results.push(r);j.humanVerification=null;await s.ctx.close().catch(()=>{});sessions.delete(j.id);run(j,j.sourceIndex+1,s.browser);res.status(202).json({accepted:true,jobId:j.id,status:'RUNNING'})});app.listen(PORT,'0.0.0.0',()=>console.log(`homatch-official-worker 1.1.0 listening on ${PORT}`));