import express from 'express';
import { chromium } from 'playwright';
const app=express();app.use(express.json({limit:'1mb'}));
const PORT=Number(process.env.PORT||3000),TOKEN=process.env.WORKER_TOKEN||'';
const jobs=new Map();
const SOURCES={tas:{name:'TAS',url:'https://tas.ge/?p=searchdocument&menuItemId=7104'},map:{name:'Cadastral Map',url:'https://ms.gov.ge/msmap/'},enreg:{name:'Entrepreneur Registry',url:'https://enreg.reestri.gov.ge/main.php?m=new_index'},mygov:{name:'MY.GOV.GE',url:'https://www.my.gov.ge/ka-ge/services/5/service/176'}};
const auth=(req,res,next)=>{if(!TOKEN||req.headers.authorization!==`Bearer ${TOKEN}`)return res.status(401).json({error:'unauthorized'});next()};
const text=async page=>{try{return (await page.locator('body').innerText({timeout:8000})).slice(0,60000)}catch{return''}};
const links=async page=>{try{return await page.locator('a[href]').evaluateAll(as=>as.slice(0,100).map(a=>({label:(a.textContent||'').trim().slice(0,180),url:a.href})).filter(x=>x.url))}catch{return[]}};
async function detectCaptcha(page){const body=(await text(page)).toLowerCase();return /captcha|recaptcha|hcaptcha|i am not a robot|არ ვარ რობოტი|უსაფრთხოების შემოწმება/.test(body)||await page.locator('iframe[src*="captcha"],iframe[src*="recaptcha"],iframe[src*="hcaptcha"]').count()>0}
async function fillLikelySearch(page,value){const sels=['input[name*="cad" i]','input[id*="cad" i]','input[placeholder*="საკადასტრო" i]','input[placeholder*="cad" i]','input[type="search"]','input[type="text"]'];for(const s of sels){const l=page.locator(s).first();if(await l.count()){try{if(await l.isVisible()){await l.fill(value);return true}}catch{}}}return false}
async function clickSearch(page){const labels=[/ძებნა/i,/მოძებნა/i,/search/i,/ძიება/i,/submit/i];for(const re of labels){const b=page.getByRole('button',{name:re}).first();try{if(await b.count()&&await b.isVisible()){await b.click();return true}}catch{}}try{const s=page.locator('button[type="submit"],input[type="submit"]').first();if(await s.count()){await s.click();return true}}catch{}return false}
async function researchSource(browser,key,value){const src=SOURCES[key],context=await browser.newContext({locale:'ka-GE',acceptDownloads:true});const page=await context.newPage();const out={source:key,name:src.name,url:src.url,status:'STARTED',retrievalMethod:'BROWSER_RETRIEVED',facts:[],links:[],pageText:'',captcha:false};try{await page.goto(src.url,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(1200);if(await detectCaptcha(page)){out.status='WAITING_HUMAN';out.captcha=true;out.pageText=(await text(page)).slice(0,8000);return out}const filled=await fillLikelySearch(page,value);if(filled){await clickSearch(page);await page.waitForTimeout(1800)}if(await detectCaptcha(page)){out.status='WAITING_HUMAN';out.captcha=true;out.pageText=(await text(page)).slice(0,8000);return out}out.pageText=await text(page);out.links=await links(page);out.status=filled?'RESULT_RETRIEVED':'PAGE_RETRIEVED';return out}catch(e){out.status='FAILED';out.error=String(e);return out}finally{await context.close()}}
async function run(job){job.status='RUNNING';job.updatedAt=new Date().toISOString();let browser;try{browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']});const keys=job.mode==='cadastral'?['tas','map','mygov']:['enreg'];for(const key of keys){job.stage=`CHECKING_${key.toUpperCase()}`;const r=await researchSource(browser,key,job.query);job.results.push(r);if(r.captcha){job.status='WAITING_HUMAN';job.stage='CAPTCHA_REQUIRED';job.humanVerification={source:key,url:r.url,message:'საჯარო წყაროს უსაფრთხოების შემოწმებაა საჭირო. დაასრულეთ შემოწმება და კვლევა ავტომატურად გაგრძელდება.'};job.updatedAt=new Date().toISOString();return}}job.status='COMPLETE';job.stage='COMPLETE'}catch(e){job.status='FAILED';job.error=String(e)}finally{if(browser)await browser.close();job.updatedAt=new Date().toISOString()}}
app.get('/health',(req,res)=>res.json({ok:true,service:'homatch-official-worker',playwright:true}));
app.post('/research',auth,(req,res)=>{const query=String(req.body?.query||'').trim(),mode=req.body?.mode==='property'?'property':'cadastral';if(!query)return res.status(400).json({error:'query required'});const id=crypto.randomUUID(),job={id,query,mode,status:'QUEUED',stage:'QUEUED',results:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};jobs.set(id,job);run(job);res.status(202).json({accepted:true,jobId:id,status:job.status})});
app.get('/research/:id',auth,(req,res)=>{const j=jobs.get(req.params.id);if(!j)return res.status(404).json({error:'not found'});res.json(j)});
app.post('/research/:id/resume',auth,(req,res)=>{const j=jobs.get(req.params.id);if(!j)return res.status(404).json({error:'not found'});if(j.status!=='WAITING_HUMAN')return res.status(409).json({error:'job is not waiting for human verification'});j.status='FAILED';j.error='Interactive CAPTCHA session handoff requires a browser-stream transport; automatic CAPTCHA solving is intentionally disabled.';j.updatedAt=new Date().toISOString();res.status(409).json(j)});
app.listen(PORT,'0.0.0.0',()=>console.log(`homatch-official-worker listening on ${PORT}`));