#!/usr/bin/env node
/*
 * Write public/sitemap.xml from the routes that are genuinely public.
 *
 * WHY IT IS GENERATED AND NOT HAND-WRITTEN
 *
 * A hand-written sitemap is correct on the day it is written and wrong
 * from the first route anybody adds. This reads routes.tsx, takes the
 * entries marked `public: true`, drops the ones with a path parameter —
 * a crawler cannot expand `:slug`, and listing the literal string would
 * publish a 404 — and writes what is left.
 *
 * WHY IT READS robots.txt RATHER THAN RESTATING IT
 *
 * A sitemap that lists a URL robots.txt blocks is a contradiction, and
 * crawlers report it as one. Two hand-kept lists drift the first time
 * somebody edits one of them, so there is one list and it lives in
 * robots.txt, which is the file a person opens when they want to know
 * what is blocked.
 *
 * WHY THE EXPAT TOPICS ARE NOT IN IT
 *
 * They live in the database and are published by an editor, so the set
 * changes without a deploy. A build-time sitemap cannot know them. Doing
 * it properly means a small endpoint that reads expat_topics and emits
 * the URLs — deliberate work, rather than a hard-coded list here that
 * goes stale the first time somebody unpublishes a topic.
 *
 * WHAT THIS DOES NOT ACHIEVE
 *
 * Homatch renders on the client. A crawler that does not execute
 * JavaScript sees an empty div at every URL in this file. Googlebot does
 * render, so the sitemap is worth having; anything else needs
 * prerendering, which is infrastructure rather than a script.
 *
 * Run: node scripts/build-sitemap.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const ROUTES = path.join(ROOT, 'src', 'routes.tsx');
const ROBOTS = path.join(ROOT, 'public', 'robots.txt');
const OUT = path.join(ROOT, 'public', 'sitemap.xml');
const ORIGIN = 'https://homatch.live';

/** Pages worth a crawler's time, ordered by how much they are worth. */
const PRIORITY = new Map([
  ['/', '1.0'],
  ['/for-expats/georgia', '0.9'],
  ['/verify', '0.8'],
  ['/mortgage', '0.8'],
  ['/investment', '0.8'],
  ['/contracts', '0.8'],
  ['/pricing', '0.7'],
  ['/developers', '0.7'],
  ['/about', '0.5'],
  ['/partners', '0.5'],
]);

/** Split on either line ending without a regex literal. */
function lines(text) {
  return text.split('\n').map((line) => line.replace('\r', ''));
}

/** The Disallow rules from robots.txt, as path prefixes. */
function disallowedPrefixes() {
  return lines(fs.readFileSync(ROBOTS, 'utf8'))
    .map((line) => line.trim())
    .filter((line) => line.toLowerCase().startsWith('disallow:'))
    .map((line) => line.slice('disallow:'.length).trim())
    .filter((value) => value.length > 0);
}

function publicPaths() {
  const blocked = disallowedPrefixes();
  const source = fs.readFileSync(ROUTES, 'utf8');
  const rows = [...source.matchAll(/\{\s*name:[^}]*?path:\s*'([^']+)'[^}]*?\}/g)];
  const paths = new Set();

  for (const row of rows) {
    const entry = row[0];
    const routePath = row[1];
    if (!/public:\s*true/.test(entry)) continue;
    // A crawler cannot expand a parameter, and the literal string is a 404.
    if (routePath.includes(':')) continue;
    // A redirect's TARGET is the canonical URL; the redirect is not.
    if (/<Navigate/.test(entry)) continue;
    // Never list something robots.txt blocks.
    if (blocked.some((prefix) => routePath === prefix || routePath.startsWith(prefix))) continue;
    paths.add(routePath);
  }

  return [...paths].sort();
}

function main() {
  const paths = publicPaths();
  if (paths.length === 0) {
    console.error('[sitemap] FATAL: no public routes found — routes.tsx may have changed shape');
    process.exit(1);
  }

  const today = new Date().toISOString().slice(0, 10);
  const urls = paths
    .map((p) =>
      [
        '  <url>',
        `    <loc>${ORIGIN}${p}</loc>`,
        `    <lastmod>${today}</lastmod>`,
        `    <priority>${PRIORITY.get(p) ?? '0.4'}</priority>`,
        '  </url>',
      ].join('\n'),
    )
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/build-sitemap.mjs from the public routes in
  src/routes.tsx, minus anything public/robots.txt disallows.
  Do not edit by hand.

  FOR EXPATS topic pages are database-published and are deliberately
  absent: a build-time file cannot know which of them are live.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

  fs.writeFileSync(OUT, xml, 'utf8');
  console.log(`[sitemap] wrote ${paths.length} public URL(s) to public/sitemap.xml`);
}

main();
