-- Minimal fixture of the production objects the Phase 2 migration touches
-- (columns copied from production information_schema, 2026-10-02).
-- Run: tests/sql/run-phase2.sh (needs a local Postgres 16).
do $$ begin create role anon; exception when duplicate_object then null; end $$; do $$ begin create role authenticated; exception when duplicate_object then null; end $$; do $$ begin create role service_role; exception when duplicate_object then null; end $$;
create extension if not exists pgcrypto;
create table public.users (id uuid primary key default gen_random_uuid(), auth_id uuid);
create or replace function public.auth_user_id() returns uuid language sql stable as $$ select nullif(current_setting('app.uid', true),'')::uuid $$;
create or replace function public.is_admin() returns boolean language sql stable as $$ select coalesce(current_setting('app.admin', true),'') = 'on' $$;
create type public.matching_job_status as enum ('queued','analysing_property','generating_queries','searching_sources','collecting_results','normalizing','deduplicating','classifying','ranking','completed','partially_completed','failed','paused','cancelled','budget_reached');
create table public.properties (id uuid primary key default gen_random_uuid());
create table public.admin_settings (id uuid default gen_random_uuid() not null, key text not null unique, value jsonb not null, description text, updated_by uuid, updated_at timestamptz default now() not null);
create table public.active_search_subscriptions (id uuid default gen_random_uuid() primary key, user_id uuid not null references public.users(id), side text not null, is_active boolean default true not null, created_at timestamptz default now() not null);
create table public.matching_jobs (id uuid default gen_random_uuid() primary key, user_id uuid not null, property_id uuid not null references public.properties(id), campaign_id uuid, idempotency_key text not null, status public.matching_job_status default 'queued' not null, progress integer default 0 not null, current_step text, created_at timestamptz default now() not null, updated_at timestamptz default now() not null, billing_grant jsonb, discovery_deadline_at timestamptz, fresh_matches_created integer default 0 not null);
create table public.discovery_query_queue (id uuid default gen_random_uuid() primary key, property_id uuid not null, platform text not null, language text not null, query text not null, status text default 'PENDING' not null check (status = any (array['PENDING','PROCESSING','RETRY_WAIT','DONE','FAILED','CANCELLED','BUDGET_REACHED'])), attempts integer default 0 not null, result_count integer default 0 not null, last_error text, created_at timestamptz default now() not null, provider text, started_at timestamptz, next_attempt_at timestamptz, metadata jsonb default '{}' not null, priority integer default 50 not null, query_kind text, claimed_at timestamptz, claim_token uuid, finished_at timestamptz, actual_cost_usd numeric, matching_job_id uuid, lease_expires_at timestamptz, cancel_reason text);
create table public.billing_plans (code text primary key);
insert into public.billing_plans values ('FREE'),('VIP'),('PREMIUM');
create table public.billable_products (code text primary key, name text, config jsonb default '{}', enabled boolean, created_at timestamptz default now(), sort_order int, updated_at timestamptz default now(), kill_switch boolean, billing_mode text, pricing_active boolean, pricing_version int, estimate_strategy text, min_gross_margin_bps int, requires_reservation boolean, standard_retail_cents numeric, min_viable_budget_credits numeric, reference_landed_cogs_cents numeric);
insert into public.billable_products values ('FIND_CLIENTS','Find Clients','{"estimate_spread_bps":3000}',true,now(),2,now(),false,'VARIABLE',true,1,'RANGE',3000,true,250,50,59);
create table public.product_plan_entitlements (product_code text references public.billable_products(code), plan_code text references public.billing_plans(code), included_per_period int default 0, period text default 'CALENDAR_MONTH', quality_tier text default 'STANDARD', result_ceiling int, provider_budget_ceiling_cents int, priority_level int default 0, config jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), primary key (product_code, plan_code));
insert into public.product_plan_entitlements(product_code,plan_code,provider_budget_ceiling_cents) values ('FIND_CLIENTS','FREE',200),('FIND_CLIENTS','VIP',600),('FIND_CLIENTS','PREMIUM',1500);
create table public.intent_profiles (id uuid primary key default gen_random_uuid());
create table public.supply_observations (id uuid primary key default gen_random_uuid());
create table public.raw_signals (id uuid primary key default gen_random_uuid());
create table public.supply_matches (id uuid primary key default gen_random_uuid(), intent_profile_id uuid references public.intent_profiles(id), signal_id uuid references public.raw_signals(id), observation_id uuid references public.supply_observations(id), property_id uuid references public.properties(id), source_kind text default 'EXTERNAL_INTELLIGENCE', compatibility text, match_score numeric);
create unique index supply_matches_signal_observation_key on public.supply_matches (signal_id, observation_id);
alter table public.supply_matches add constraint supply_matches_one_supply_kind check ((source_kind='INTERNAL_HOMATCH' and property_id is not null and signal_id is null and observation_id is null) or (source_kind='EXTERNAL_INTELLIGENCE' and property_id is null and signal_id is not null and observation_id is not null)) not valid;
