#!/usr/bin/env bash
# Apply the FIND BUYERS migration TWICE on the Phase 2 fixture, then run the
# behavioural checks. Needs Postgres 16 binaries (same harness as run-phase2.sh).
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"; root="$here/../.."
dir="${PGFIX_DIR:-/var/tmp/hm-pg}"; port="${PGFIX_PORT:-54329}"; bin="${PGBIN:-/usr/lib/postgresql/16/bin}"
if ! psql -h "$dir" -p "$port" -U postgres -tAc 'select 1' >/dev/null 2>&1; then
  rm -rf "$dir"; mkdir -p "$dir"; chown postgres "$dir" 2>/dev/null || true
  su postgres -c "$bin/initdb -D $dir/data -A trust >/dev/null && $bin/pg_ctl -D $dir/data -o '-p $port -k $dir' -l $dir/log start >/dev/null"
  sleep 2
fi
P="psql -h $dir -p $port -U postgres -v ON_ERROR_STOP=1 -q"
$P -c "drop database if exists fbfx" -c "create database fbfx"
$P -d fbfx -f "$here/phase2_fixture.sql"
$P -d fbfx -1 -f "$root/supabase/migrations/20261009100000_phase2_universal_discovery.sql" 2>/dev/null
$P -d fbfx -f "$here/find_buyers_fixture.sql"
M0="$root/supabase/migrations/20261014090000_cost_provider_apify_memo23.sql"
M="$root/supabase/migrations/20261014100000_find_buyers_social_intelligence.sql"
$P -d fbfx -1 -f "$M0"
$P -d fbfx -1 -f "$M0"
$P -d fbfx -1 -f "$M"
$P -d fbfx -1 -f "$M"
M2="$root/supabase/migrations/20261015090000_find_buyers_global_run_slots.sql"
$P -d fbfx -1 -f "$M2"
$P -d fbfx -1 -f "$M2"
M3="$root/supabase/migrations/20261016090000_find_buyers_lifecycle_truth.sql"
$P -d fbfx -f "$here/find_buyers_lifecycle_fixture.sql"
$P -d fbfx -1 -f "$M3"
$P -d fbfx -1 -f "$M3"
$P -d fbfx -f "$here/find_buyers.sql"
$P -d fbfx -f "$here/find_buyers_slots.sql"
$P -d fbfx -f "$here/find_buyers_lifecycle.sql"
M4="$root/supabase/migrations/20261017090000_find_buyers_current_leads_one_active_search.sql"
$P -d fbfx -f "$here/find_buyers_current_leads_fixture.sql"
$P -d fbfx -1 -f "$M4"
$P -d fbfx -1 -f "$M4"
$P -d fbfx -f "$here/find_buyers_current_leads.sql"
M5="$root/supabase/migrations/20261018090000_find_buyers_source_truth.sql"
$P -d fbfx -1 -f "$M5"
$P -d fbfx -1 -f "$M5"
$P -d fbfx -f "$here/find_buyers_source_truth.sql"
M6="$root/supabase/migrations/20261021090000_find_buyers_last_search_state.sql"
$P -d fbfx -f "$here/find_buyers_last_search_fixture.sql"
$P -d fbfx -1 -f "$M6"
$P -d fbfx -1 -f "$M6"
$P -d fbfx -f "$here/find_buyers_last_search.sql"
M7="$root/supabase/migrations/20261022090000_find_buyers_source_network.sql"
$P -d fbfx -f "$here/find_buyers_source_network_fixture.sql"
$P -d fbfx -1 -f "$M7"
$P -d fbfx -1 -f "$M7"
$P -d fbfx -f "$here/find_buyers_source_network.sql"
M8="$root/supabase/migrations/20261024090000_find_buyers_qualification.sql"
$P -d fbfx -1 -f "$M8"
$P -d fbfx -1 -f "$M8"
$P -d fbfx -f "$here/find_buyers_qualification.sql"
