#!/usr/bin/env node
// Turn the content modules into idempotent SQL.
//
// WHY SQL AND NOT A SUPABASE CLIENT
//
// The content tables are admin-write only, and correctly so: nothing with an
// anon key should be able to publish a legal topic. Seeding therefore runs
// with elevated access, and the safest shape for that is a reviewable SQL
// file rather than a script holding a service key.
//
// WHY EVERY STATEMENT IS AN UPSERT
//
// This runs again every time the content changes. A seed that can only be
// run once is a seed that gets edited by hand in production the second time
// somebody fixes a typo, and then the repository stops describing what is
// live. Slugs, fact keys and citation URLs are the natural keys.
//
// Run: node scripts/expat-content/build-seed.mjs > /path/to/seed.sql

import { SOURCES } from './sources.mjs';
import { MOVE_TOPICS } from './topics-move.mjs';
import { LIVE_TOPICS } from './topics-live.mjs';
import { MONEY_TOPICS } from './topics-money.mjs';
import { COST_OBSERVATIONS } from './cost-observations.mjs';

const TOPICS = [...MOVE_TOPICS, ...LIVE_TOPICS, ...MONEY_TOPICS];
const LOCALES = ['en', 'ka', 'ru', 'tr', 'ar', 'he'];

/** Single-quote escaping, the only escaping SQL literals need. */
const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (v) =>
  v === null || v === undefined ? 'null' : `array[${v.map((x) => q(x)).join(',')}]::text[]`;

const out = [];
const w = (s) => out.push(s);

w('-- Generated by scripts/expat-content/build-seed.mjs. Do not edit by hand.');
w('-- Every statement is an upsert on a natural key, so re-running is safe.');
w('begin;');
w('');

/* ── Citations ────────────────────────────────────────────────────────── */
w('-- Sources. Keyed on url, which is unique per source in this set.');
for (const s of Object.values(SOURCES)) {
  w(`insert into public.expat_citations
  (publisher, url, official, published_on, effective_from, observed_at, language, excerpt)
values (${q(s.publisher)}, ${q(s.url)}, ${s.official}, ${q(s.publishedOn)}, ${q(s.effectiveFrom)},
        ${q(s.observedAt)}::timestamptz, ${q(s.language)}, ${q(s.excerpt)})
on conflict do nothing;`);
}
w('');
// url has no unique constraint (a source can legitimately be cited twice with
// different observation dates), so the upsert above is a no-op on re-run only
// if nothing changed. Collapse any duplicates this creates, keeping the oldest.
w(`-- Keep one row per (publisher, url): re-running must not accumulate copies.
delete from public.expat_citations a
using public.expat_citations b
where a.publisher = b.publisher
  and a.url is not distinct from b.url
  and a.ctid > b.ctid
  and not exists (select 1 from public.expat_fact_citations fc where fc.citation_id = a.id)
  and not exists (select 1 from public.expat_cost_observations co where co.citation_id = a.id)
  and not exists (select 1 from public.expat_places p where p.citation_id = a.id);`);
w('');

/* ── Topics ───────────────────────────────────────────────────────────── */
for (const t of TOPICS) {
  const missing = LOCALES.filter((l) => !t.content[l]);
  if (missing.length > 0) {
    throw new Error(`topic ${t.slug} is missing locales: ${missing.join(', ')}`);
  }
  w(`-- ${t.slug}`);
  w(`insert into public.expat_topics
  (slug, country, domain, pathway, content, fact_class, register, sort_order,
   published, needs_review, review_reason, last_verified_at, review_due_at)
values (${q(t.slug)}, 'GE', ${q(t.domain)}, ${q(t.pathway)}, ${j(t.content)},
        ${q(t.factClass)}, ${q(t.register)}, ${t.sortOrder},
        true, ${t.needsReview ? 'true' : 'false'}, ${q(t.reviewReason ?? null)},
        now(), now() + interval '90 days')
on conflict (slug) do update set
  domain = excluded.domain,
  pathway = excluded.pathway,
  content = excluded.content,
  fact_class = excluded.fact_class,
  register = excluded.register,
  sort_order = excluded.sort_order,
  published = excluded.published,
  needs_review = excluded.needs_review,
  review_reason = excluded.review_reason,
  last_verified_at = excluded.last_verified_at,
  review_due_at = excluded.review_due_at,
  updated_at = now();`);

  for (const f of t.facts ?? []) {
    const stmtMissing = LOCALES.filter((l) => !f.statement[l]);
    if (stmtMissing.length > 0) {
      throw new Error(`fact ${t.slug}/${f.key} is missing locales: ${stmtMissing.join(', ')}`);
    }
    w(`insert into public.expat_topic_facts
  (topic_id, fact_key, fact_class, register, availability, statement, value,
   applies_to_nationalities, needs_review)
select id, ${q(f.key)}, ${q(f.factClass)}, ${q(f.register)}, ${q(f.availability)},
       ${j(f.statement)}, ${f.value ? j(f.value) : 'null'}, ${arr(f.appliesTo ?? null)},
       ${f.needsReview ? 'true' : 'false'}
from public.expat_topics where slug = ${q(t.slug)}
on conflict (topic_id, fact_key) do update set
  fact_class = excluded.fact_class,
  register = excluded.register,
  availability = excluded.availability,
  statement = excluded.statement,
  value = excluded.value,
  applies_to_nationalities = excluded.applies_to_nationalities,
  needs_review = excluded.needs_review,
  updated_at = now();`);

    for (const sourceKey of f.sources ?? []) {
      const src = SOURCES[sourceKey];
      if (!src) throw new Error(`fact ${t.slug}/${f.key} cites unknown source ${sourceKey}`);
      w(`insert into public.expat_fact_citations (fact_id, citation_id)
select f.id, c.id
from public.expat_topic_facts f
join public.expat_topics t on t.id = f.topic_id and t.slug = ${q(t.slug)}
cross join lateral (
  select id from public.expat_citations
  where publisher = ${q(src.publisher)} and url is not distinct from ${q(src.url)}
  order by created_at limit 1) c
where f.fact_key = ${q(f.key)}
on conflict do nothing;`);
    }
  }
  w('');
}

/* ── Cost observations ────────────────────────────────────────────────── */
w('-- Observed prices. Supersede rather than overwrite, so a change is visible.');
for (const o of COST_OBSERVATIONS) {
  const src = SOURCES[o.source];
  if (!src) throw new Error(`observation ${o.city}/${o.category} cites unknown source ${o.source}`);
  w(`update public.expat_cost_observations set status = 'SUPERSEDED'
where status = 'CURRENT' and country = 'GE' and city = ${q(o.city)}
  and coalesce(district,'') = ${q(o.district ?? '')} and category = ${q(o.category)} and unit = ${q(o.unit)}
  and (low, high, observed_at) is distinct from (${o.low}::numeric, ${o.high}::numeric, ${q(o.observedAt)}::timestamptz);`);
  w(`insert into public.expat_cost_observations
  (country, city, district, category, low, high, currency, unit,
   sample_size, source_count, observed_at, citation_id, status, notes)
select 'GE', ${q(o.city)}, ${q(o.district ?? null)}, ${q(o.category)}, ${o.low}, ${o.high},
       ${q(o.currency)}, ${q(o.unit)}, ${o.sampleSize}, ${o.sourceCount},
       ${q(o.observedAt)}::timestamptz, c.id, 'CURRENT', ${q(o.notes ?? null)}
from (select id from public.expat_citations
      where publisher = ${q(src.publisher)} and url is not distinct from ${q(src.url)}
      order by created_at limit 1) c
where not exists (
  select 1 from public.expat_cost_observations e
  where e.status = 'CURRENT' and e.country = 'GE' and e.city = ${q(o.city)}
    and coalesce(e.district,'') = ${q(o.district ?? '')}
    and e.category = ${q(o.category)} and e.unit = ${q(o.unit)});`);
}
w('');
w('commit;');

process.stdout.write(out.join('\n') + '\n');
