-- 20260829130009_secure_internal_helper_functions
-- Applied directly to production before repository migration-history synchronization.
-- This manifest intentionally contains no SQL; the production schema is captured by later idempotent migrations.
