-- Seed data: real, web-search-verified Telegram/Facebook communities focused on
-- Georgian real estate (Tbilisi/Batumi). Every canonical_url below was found
-- via live web search pointing to a real, currently-existing group/channel —
-- none are guessed or synthesized. member_count is set only where a source
-- actually reported one; otherwise left null rather than fabricated.
-- posting_policy/posting_allowed are marked UNKNOWN/null wherever the
-- group-vs-broadcast-channel distinction could not be confirmed, and CLOSED
-- for channels whose naming (©, "notifier") strongly signals admin-only
-- broadcast rather than member posting — these still appear as valuable
-- discovery/visibility targets even though a seller cannot self-post there.
INSERT INTO public.community_directory
  (platform, canonical_url, name, description, language, country, city, member_count, posting_policy, posting_allowed, allows_auto_post, tags, topics, is_active, last_verified_at, metadata)
VALUES
  ('TELEGRAM', 'https://t.me/rent_tbilisi_ge', 'Rent in Tbilisi 🇬🇪 Flats', 'Telegram broadcast channel listing Tbilisi apartments for rent.', 'en', 'Georgia', 'Tbilisi', 8793, 'CLOSED', false, false, ARRAY['rent'], ARRAY['real_estate'], true, now(), '{"verification_source":"telemetr.io","note":"Broadcast channel (©) — discovery only, not open for member posts."}'::jsonb),
  ('TELEGRAM', 'https://t.me/sale_in_tbilisi', 'Sale in Tbilisi 🇬🇪 Flats', 'Telegram broadcast channel listing Tbilisi apartments for sale (sister channel to Rent in Tbilisi).', 'en', 'Georgia', 'Tbilisi', NULL, 'CLOSED', false, false, ARRAY['sale'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search","note":"Broadcast channel (©) — discovery only, not open for member posts."}'::jsonb),
  ('TELEGRAM', 'https://t.me/apartments_ge', 'Квартиры Батуми / Тбилиси (My Apartments)', 'Aggregated rental and sale listings across Batumi and Tbilisi.', 'ru', 'Georgia', NULL, 11739, 'UNKNOWN', NULL, false, ARRAY['rent','sale'], ARRAY['real_estate'], true, now(), '{"verification_source":"telemetr.io"}'::jsonb),
  ('TELEGRAM', 'https://t.me/apart_notifier_tbilisi', 'Квартиры в аренду | Тбилиси', 'Auto-aggregated Tbilisi rental listings, budget-focused.', 'ru', 'Georgia', 'Tbilisi', 1838, 'CLOSED', false, false, ARRAY['rent'], ARRAY['real_estate'], true, now(), '{"verification_source":"telemetr.io","note":"Naming indicates an auto-notifier/aggregator channel, not open for member posts."}'::jsonb),
  ('TELEGRAM', 'https://t.me/tbilisi_apartments', 'Tbilisi Apartments', 'Tbilisi apartment listings channel/group.', NULL, 'Georgia', 'Tbilisi', NULL, 'UNKNOWN', NULL, false, ARRAY['rent','sale'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search","note":"Existence confirmed; posting policy and language unconfirmed."}'::jsonb),
  ('TELEGRAM', 'https://t.me/arenda_kvartir_tbilisi', 'Аренда квартир Тбилиси', 'Tbilisi apartment rental group/channel.', 'ru', 'Georgia', 'Tbilisi', NULL, 'UNKNOWN', NULL, false, ARRAY['rent'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search","note":"Existence confirmed; posting policy unconfirmed."}'::jsonb),
  ('TELEGRAM', 'https://t.me/batumi_in', 'Batumi INvest', 'Batumi property investment/sale channel.', NULL, 'Georgia', 'Batumi', NULL, 'UNKNOWN', NULL, false, ARRAY['sale','investment'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search","note":"Existence confirmed; posting policy unconfirmed."}'::jsonb),
  ('TELEGRAM', 'https://t.me/arendabatumi', 'Аренда Батуми', 'Batumi apartment rental channel/group.', 'ru', 'Georgia', 'Batumi', NULL, 'UNKNOWN', NULL, false, ARRAY['rent'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search","note":"Existence confirmed; posting policy unconfirmed."}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/633889243636417', 'Apartment for Rent in Tbilisi (Georgia)', 'Facebook group for Tbilisi apartment rentals.', 'en', 'Georgia', 'Tbilisi', NULL, 'APPROVAL_REQUIRED', true, false, ARRAY['rent'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search","note":"Member count not visible to unauthenticated search."}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/561675125047094/', 'Apartments & Houses for rent in Tbilisi | RENTA', 'Facebook group for Tbilisi rentals.', 'en', 'Georgia', 'Tbilisi', NULL, 'APPROVAL_REQUIRED', true, false, ARRAY['rent'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search"}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/288748245046329', 'Apartments for Rent and Sale in Tbilisi Georgia', 'Facebook group covering both Tbilisi rentals and sales.', 'en', 'Georgia', 'Tbilisi', NULL, 'APPROVAL_REQUIRED', true, false, ARRAY['rent','sale'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search"}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/3381291802085129/', 'Apartments / Houses / Flats for Rent in Tbilisi, Georgia', 'Facebook group for Tbilisi rentals.', 'en', 'Georgia', 'Tbilisi', NULL, 'APPROVAL_REQUIRED', true, false, ARRAY['rent'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search"}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/accommodation.tbilisi/', 'For Rent Apartments & Houses — Accommodation in Tbilisi', 'Facebook group for Tbilisi accommodation rentals.', 'en', 'Georgia', 'Tbilisi', NULL, 'APPROVAL_REQUIRED', true, false, ARRAY['rent'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search"}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/rentapartmentintbilisi/', 'Rent Apartment House Commercial Parking in Tbilisi Georgia', 'Facebook group for Tbilisi rentals including commercial/parking.', 'en', 'Georgia', 'Tbilisi', NULL, 'APPROVAL_REQUIRED', true, false, ARRAY['rent','commercial'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search"}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/2877273609072240/', 'Batumi Apartments | Sale & Rent', 'Facebook group covering Batumi sales and rentals.', 'en', 'Georgia', 'Batumi', NULL, 'APPROVAL_REQUIRED', true, false, ARRAY['rent','sale'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search"}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/661477109393753/', 'Batumi! Apartments For Rent (ბათუმი! ბინების გაქირავება)', 'Facebook group for Batumi rentals, Georgian/English.', NULL, 'Georgia', 'Batumi', NULL, 'APPROVAL_REQUIRED', true, false, ARRAY['rent'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search"}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/761689861399478/', 'ბინები ბათუმში / Sale & Rent in Batumi / Квартиры в Батуми', 'Facebook group covering Batumi sales and rentals, multilingual.', NULL, 'Georgia', 'Batumi', NULL, 'APPROVAL_REQUIRED', true, false, ARRAY['rent','sale'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search"}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/1553863908446451/', 'Apartments / Houses / Flats for Rent in Batumi, Georgia', 'Facebook group for Batumi rentals.', 'en', 'Georgia', 'Batumi', NULL, 'APPROVAL_REQUIRED', true, false, ARRAY['rent'], ARRAY['real_estate'], true, now(), '{"verification_source":"web_search"}'::jsonb),
  ('FACEBOOK', 'https://www.facebook.com/groups/ExpatsInTbilisi', 'ExpatsInTbilisi', 'General Tbilisi expat community group; property discussion is occasional, not a dedicated listings group.', 'en', 'Georgia', 'Tbilisi', NULL, 'UNKNOWN', NULL, false, ARRAY['general','expat'], ARRAY['real_estate','community'], true, now(), '{"verification_source":"web_search","note":"Not a dedicated real-estate group — lower relevance, kept for expat-buyer visibility."}'::jsonb)
ON CONFLICT DO NOTHING;
